// Code generated by protoc-gen-go.
// source: condor_proxy.proto
// DO NOT EDIT!

/*
Package tes_condor_proxy is a generated protocol buffer package.

It is generated from these files:
	condor_proxy.proto

It has these top-level messages:
	StartWorkerRequest
	StartWorkerResponse
*/
package tes_condor_proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartWorkerRequest struct {
	SchedAddr string `protobuf:"bytes,1,opt,name=SchedAddr" json:"SchedAddr,omitempty"`
}

func (m *StartWorkerRequest) Reset()                    { *m = StartWorkerRequest{} }
func (m *StartWorkerRequest) String() string            { return proto.CompactTextString(m) }
func (*StartWorkerRequest) ProtoMessage()               {}
func (*StartWorkerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartWorkerRequest) GetSchedAddr() string {
	if m != nil {
		return m.SchedAddr
	}
	return ""
}

type StartWorkerResponse struct {
}

func (m *StartWorkerResponse) Reset()                    { *m = StartWorkerResponse{} }
func (m *StartWorkerResponse) String() string            { return proto.CompactTextString(m) }
func (*StartWorkerResponse) ProtoMessage()               {}
func (*StartWorkerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*StartWorkerRequest)(nil), "tes.condor.proxy.StartWorkerRequest")
	proto.RegisterType((*StartWorkerResponse)(nil), "tes.condor.proxy.StartWorkerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CondorProxy service

type CondorProxyClient interface {
	StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*StartWorkerResponse, error)
}

type condorProxyClient struct {
	cc *grpc.ClientConn
}

func NewCondorProxyClient(cc *grpc.ClientConn) CondorProxyClient {
	return &condorProxyClient{cc}
}

func (c *condorProxyClient) StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*StartWorkerResponse, error) {
	out := new(StartWorkerResponse)
	err := grpc.Invoke(ctx, "/tes.condor.proxy.CondorProxy/StartWorker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CondorProxy service

type CondorProxyServer interface {
	StartWorker(context.Context, *StartWorkerRequest) (*StartWorkerResponse, error)
}

func RegisterCondorProxyServer(s *grpc.Server, srv CondorProxyServer) {
	s.RegisterService(&_CondorProxy_serviceDesc, srv)
}

func _CondorProxy_StartWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CondorProxyServer).StartWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tes.condor.proxy.CondorProxy/StartWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CondorProxyServer).StartWorker(ctx, req.(*StartWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CondorProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tes.condor.proxy.CondorProxy",
	HandlerType: (*CondorProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorker",
			Handler:    _CondorProxy_StartWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "condor_proxy.proto",
}

func init() { proto.RegisterFile("condor_proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0xcf, 0x4b,
	0xc9, 0x2f, 0x8a, 0x2f, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x03, 0x92, 0x25, 0xf9, 0x42, 0x02, 0x25,
	0xa9, 0xc5, 0x7a, 0x10, 0x71, 0x3d, 0xb0, 0xb8, 0x92, 0x11, 0x97, 0x50, 0x70, 0x49, 0x62, 0x51,
	0x49, 0x78, 0x7e, 0x51, 0x76, 0x6a, 0x51, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x0c,
	0x17, 0x67, 0x70, 0x72, 0x46, 0x6a, 0x8a, 0x63, 0x4a, 0x4a, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x42, 0x40, 0x49, 0x94, 0x4b, 0x18, 0x45, 0x4f, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa,
	0x51, 0x36, 0x17, 0xb7, 0x33, 0xd8, 0xe8, 0x00, 0x90, 0xc9, 0x42, 0x31, 0x5c, 0xdc, 0x48, 0xaa,
	0x84, 0x54, 0xf4, 0xd0, 0xed, 0xd6, 0xc3, 0xb4, 0x58, 0x4a, 0x95, 0x80, 0x2a, 0x88, 0x55, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x0f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0x9a, 0xe6, 0x82,
	0xe6, 0x00, 0x00, 0x00,
}
