version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates against the `develop` branch
    target-branch: "develop"
