version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    groups:
      dependabot:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/webdash"
    schedule:
      interval: "daily"
    target-branch: "develop"
    groups:
      npm-deps:
        patterns:
          - "*"

