# .goreleaser.yaml
builds:
  - binary: funnel
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: >
      -X github.com/ohsu-comp-bio/funnel/version.BuildDate={{.Date}}
      -X github.com/ohsu-comp-bio/funnel/version.GitCommit={{.ShortCommit}}
      -X github.com/ohsu-comp-bio/funnel/version.GitBranch={{.Env.GIT_BRANCH}}
      -X github.com/ohsu-comp-bio/funnel/version.GitUpstream={{.Env.GIT_UPSTREAM}}
      -X github.com/ohsu-comp-bio/funnel/version.Version={{.Version}}

dist: build/release

release:
  draft: false
  prerelease: auto

# Remove env_files section since we're using environment variables
# env_files:
#   github_token: .github_token

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

# Add changelog generation
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: ohsu-comp-bio
      name: homebrew-formula
    directory: Formula
    skip_upload: false  # Enable if you want Homebrew integration
    description: "distributed task execution toolkit"
    homepage: "https://ohsu-comp-bio.github.io/funnel/"
    license: "Apache-2.0"  # Add license
    install: |
      bin.install "funnel"
    test: |
      system "#{bin}/funnel", "version"
