builds:
  - binary: funnel
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: >
      -X github.com/ohsu-comp-bio/funnel/version.BuildDate={{.Date}}
      -X github.com/ohsu-comp-bio/funnel/version.GitCommit={{.ShortCommit}}
      -X github.com/ohsu-comp-bio/funnel/version.GitBranch={{.Env.GIT_BRANCH}}
      -X github.com/ohsu-comp-bio/funnel/version.GitUpstream={{.Env.GIT_UPSTREAM}}
      -X github.com/ohsu-comp-bio/funnel/version.Version={{.Version}}

dist: build/release

release:
  draft: true

env_files:
  github_token: .github_token

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ohsucompbio/funnel:{{.Version}}"
    dockerfile: ./Dockerfile
  - goos: linux
    goarch: amd64
    image_templates:
      - "ohsucompbio/funnel-dind:{{.Version}}"
    dockerfile: ./Dockerfile.dind
  - goos: linux
    goarch: amd64
    image_templates:
      - "ohsucompbio/funnel-dind-rootless:{{.Version}}"
    dockerfile: ./Dockerfile.dind-rootless

brews:
  - github:
      owner: ohsu-comp-bio
      name: homebrew-formula
    folder: Formula
    skip_upload: true
    description: "distributed task execution toolkit"
    homepage: "https://ohsu-comp-bio.github.io/funnel/"
    install: |
      bin.install "funnel"
    test: |
      system "#{bin}/funnel", "version"
