preset: angular
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean
branches:
  - "main"
  - "master"
  - "feature/plugins"
  - "feature/semver-release"
