// Code generated by protoc-gen-go.
// source: funnel.proto
// DO NOT EDIT!

/*
Package funnel is a generated protocol buffer package.

It is generated from these files:
	funnel.proto

It has these top-level messages:
	Resources
	Worker
	TaskWrapper
	UpdateExecutorLogsRequest
	UpdateExecutorLogsResponse
	QueuedTaskInfoRequest
	QueuedTaskInfo
	GetWorkersRequest
	GetWorkersResponse
	UpdateWorkerResponse
	GetWorkerRequest
*/
package funnel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tes "github.com/ohsu-comp-bio/funnel/proto/tes"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkerState int32

const (
	WorkerState_Uninitialized WorkerState = 0
	WorkerState_Alive         WorkerState = 1
	WorkerState_Dead          WorkerState = 2
	WorkerState_Gone          WorkerState = 3
	WorkerState_Initializing  WorkerState = 4
)

var WorkerState_name = map[int32]string{
	0: "Uninitialized",
	1: "Alive",
	2: "Dead",
	3: "Gone",
	4: "Initializing",
}
var WorkerState_value = map[string]int32{
	"Uninitialized": 0,
	"Alive":         1,
	"Dead":          2,
	"Gone":          3,
	"Initializing":  4,
}

func (x WorkerState) String() string {
	return proto.EnumName(WorkerState_name, int32(x))
}
func (WorkerState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Resources struct {
	Cpus uint32 `protobuf:"varint,1,opt,name=cpus" json:"cpus,omitempty"`
	// In GB
	Ram float64 `protobuf:"fixed64,2,opt,name=ram" json:"ram,omitempty"`
	// In GB
	Disk float64 `protobuf:"fixed64,3,opt,name=disk" json:"disk,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resources) GetCpus() uint32 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Resources) GetRam() float64 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *Resources) GetDisk() float64 {
	if m != nil {
		return m.Disk
	}
	return 0
}

type Worker struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Task ID -> TaskWrapper
	Tasks       map[string]*TaskWrapper `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources   *Resources              `protobuf:"bytes,5,opt,name=resources" json:"resources,omitempty"`
	Available   *Resources              `protobuf:"bytes,6,opt,name=available" json:"available,omitempty"`
	LastPing    int64                   `protobuf:"varint,7,opt,name=last_ping,json=lastPing" json:"last_ping,omitempty"`
	State       WorkerState             `protobuf:"varint,8,opt,name=state,enum=funnel.WorkerState" json:"state,omitempty"`
	Preemptible bool                    `protobuf:"varint,9,opt,name=preemptible" json:"preemptible,omitempty"`
	// TODO where does this get updated?
	ActivePorts []int32 `protobuf:"varint,10,rep,packed,name=active_ports,json=activePorts" json:"active_ports,omitempty"`
	Zone        string  `protobuf:"bytes,11,opt,name=zone" json:"zone,omitempty"`
	// Hostname of the worker host.
	// TODO
	Hostname string `protobuf:"bytes,13,opt,name=hostname" json:"hostname,omitempty"`
	// Version of the record in the database. Used to prevent write conflicts.
	Version  int64             `protobuf:"varint,14,opt,name=version" json:"version,omitempty"`
	Metadata map[string]string `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Worker) Reset()                    { *m = Worker{} }
func (m *Worker) String() string            { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()               {}
func (*Worker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Worker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Worker) GetTasks() map[string]*TaskWrapper {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Worker) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Worker) GetAvailable() *Resources {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *Worker) GetLastPing() int64 {
	if m != nil {
		return m.LastPing
	}
	return 0
}

func (m *Worker) GetState() WorkerState {
	if m != nil {
		return m.State
	}
	return WorkerState_Uninitialized
}

func (m *Worker) GetPreemptible() bool {
	if m != nil {
		return m.Preemptible
	}
	return false
}

func (m *Worker) GetActivePorts() []int32 {
	if m != nil {
		return m.ActivePorts
	}
	return nil
}

func (m *Worker) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Worker) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Worker) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Worker) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// TODO is there a nice way to avoid this wrapper? Maybe protobuf extensions?
//      or use metadata field of Task?
type TaskWrapper struct {
	Task *tes.Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	Auth string    `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
}

func (m *TaskWrapper) Reset()                    { *m = TaskWrapper{} }
func (m *TaskWrapper) String() string            { return proto.CompactTextString(m) }
func (*TaskWrapper) ProtoMessage()               {}
func (*TaskWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TaskWrapper) GetTask() *tes.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *TaskWrapper) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

type UpdateExecutorLogsRequest struct {
	Id       string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Step     int64            `protobuf:"varint,2,opt,name=step" json:"step,omitempty"`
	Log      *tes.ExecutorLog `protobuf:"bytes,4,opt,name=log" json:"log,omitempty"`
	WorkerId string           `protobuf:"bytes,5,opt,name=worker_id,json=workerId" json:"worker_id,omitempty"`
}

func (m *UpdateExecutorLogsRequest) Reset()                    { *m = UpdateExecutorLogsRequest{} }
func (m *UpdateExecutorLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateExecutorLogsRequest) ProtoMessage()               {}
func (*UpdateExecutorLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateExecutorLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateExecutorLogsRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *UpdateExecutorLogsRequest) GetLog() *tes.ExecutorLog {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *UpdateExecutorLogsRequest) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

type UpdateExecutorLogsResponse struct {
}

func (m *UpdateExecutorLogsResponse) Reset()                    { *m = UpdateExecutorLogsResponse{} }
func (m *UpdateExecutorLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateExecutorLogsResponse) ProtoMessage()               {}
func (*UpdateExecutorLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type QueuedTaskInfoRequest struct {
	MaxTasks int32 `protobuf:"varint,1,opt,name=max_tasks,json=maxTasks" json:"max_tasks,omitempty"`
}

func (m *QueuedTaskInfoRequest) Reset()                    { *m = QueuedTaskInfoRequest{} }
func (m *QueuedTaskInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*QueuedTaskInfoRequest) ProtoMessage()               {}
func (*QueuedTaskInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueuedTaskInfoRequest) GetMaxTasks() int32 {
	if m != nil {
		return m.MaxTasks
	}
	return 0
}

type QueuedTaskInfo struct {
	Inputs    []string       `protobuf:"bytes,1,rep,name=inputs" json:"inputs,omitempty"`
	Resources *tes.Resources `protobuf:"bytes,2,opt,name=resources" json:"resources,omitempty"`
}

func (m *QueuedTaskInfo) Reset()                    { *m = QueuedTaskInfo{} }
func (m *QueuedTaskInfo) String() string            { return proto.CompactTextString(m) }
func (*QueuedTaskInfo) ProtoMessage()               {}
func (*QueuedTaskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueuedTaskInfo) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *QueuedTaskInfo) GetResources() *tes.Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

type GetWorkersRequest struct {
}

func (m *GetWorkersRequest) Reset()                    { *m = GetWorkersRequest{} }
func (m *GetWorkersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetWorkersRequest) ProtoMessage()               {}
func (*GetWorkersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetWorkersResponse struct {
	Workers []*Worker `protobuf:"bytes,1,rep,name=workers" json:"workers,omitempty"`
}

func (m *GetWorkersResponse) Reset()                    { *m = GetWorkersResponse{} }
func (m *GetWorkersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetWorkersResponse) ProtoMessage()               {}
func (*GetWorkersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetWorkersResponse) GetWorkers() []*Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

type UpdateWorkerResponse struct {
}

func (m *UpdateWorkerResponse) Reset()                    { *m = UpdateWorkerResponse{} }
func (m *UpdateWorkerResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateWorkerResponse) ProtoMessage()               {}
func (*UpdateWorkerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetWorkerRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetWorkerRequest) Reset()                    { *m = GetWorkerRequest{} }
func (m *GetWorkerRequest) String() string            { return proto.CompactTextString(m) }
func (*GetWorkerRequest) ProtoMessage()               {}
func (*GetWorkerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetWorkerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Resources)(nil), "funnel.Resources")
	proto.RegisterType((*Worker)(nil), "funnel.Worker")
	proto.RegisterType((*TaskWrapper)(nil), "funnel.TaskWrapper")
	proto.RegisterType((*UpdateExecutorLogsRequest)(nil), "funnel.UpdateExecutorLogsRequest")
	proto.RegisterType((*UpdateExecutorLogsResponse)(nil), "funnel.UpdateExecutorLogsResponse")
	proto.RegisterType((*QueuedTaskInfoRequest)(nil), "funnel.QueuedTaskInfoRequest")
	proto.RegisterType((*QueuedTaskInfo)(nil), "funnel.QueuedTaskInfo")
	proto.RegisterType((*GetWorkersRequest)(nil), "funnel.GetWorkersRequest")
	proto.RegisterType((*GetWorkersResponse)(nil), "funnel.GetWorkersResponse")
	proto.RegisterType((*UpdateWorkerResponse)(nil), "funnel.UpdateWorkerResponse")
	proto.RegisterType((*GetWorkerRequest)(nil), "funnel.GetWorkerRequest")
	proto.RegisterEnum("funnel.WorkerState", WorkerState_name, WorkerState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scheduler service

type SchedulerClient interface {
	GetQueueInfo(ctx context.Context, in *QueuedTaskInfoRequest, opts ...grpc.CallOption) (Scheduler_GetQueueInfoClient, error)
	UpdateExecutorLogs(ctx context.Context, in *UpdateExecutorLogsRequest, opts ...grpc.CallOption) (*UpdateExecutorLogsResponse, error)
	UpdateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*UpdateWorkerResponse, error)
	GetWorkers(ctx context.Context, in *GetWorkersRequest, opts ...grpc.CallOption) (*GetWorkersResponse, error)
	GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*Worker, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) GetQueueInfo(ctx context.Context, in *QueuedTaskInfoRequest, opts ...grpc.CallOption) (Scheduler_GetQueueInfoClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Scheduler_serviceDesc.Streams[0], c.cc, "/funnel.Scheduler/GetQueueInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &schedulerGetQueueInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Scheduler_GetQueueInfoClient interface {
	Recv() (*QueuedTaskInfo, error)
	grpc.ClientStream
}

type schedulerGetQueueInfoClient struct {
	grpc.ClientStream
}

func (x *schedulerGetQueueInfoClient) Recv() (*QueuedTaskInfo, error) {
	m := new(QueuedTaskInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *schedulerClient) UpdateExecutorLogs(ctx context.Context, in *UpdateExecutorLogsRequest, opts ...grpc.CallOption) (*UpdateExecutorLogsResponse, error) {
	out := new(UpdateExecutorLogsResponse)
	err := grpc.Invoke(ctx, "/funnel.Scheduler/UpdateExecutorLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UpdateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*UpdateWorkerResponse, error) {
	out := new(UpdateWorkerResponse)
	err := grpc.Invoke(ctx, "/funnel.Scheduler/UpdateWorker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetWorkers(ctx context.Context, in *GetWorkersRequest, opts ...grpc.CallOption) (*GetWorkersResponse, error) {
	out := new(GetWorkersResponse)
	err := grpc.Invoke(ctx, "/funnel.Scheduler/GetWorkers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*Worker, error) {
	out := new(Worker)
	err := grpc.Invoke(ctx, "/funnel.Scheduler/GetWorker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerServer interface {
	GetQueueInfo(*QueuedTaskInfoRequest, Scheduler_GetQueueInfoServer) error
	UpdateExecutorLogs(context.Context, *UpdateExecutorLogsRequest) (*UpdateExecutorLogsResponse, error)
	UpdateWorker(context.Context, *Worker) (*UpdateWorkerResponse, error)
	GetWorkers(context.Context, *GetWorkersRequest) (*GetWorkersResponse, error)
	GetWorker(context.Context, *GetWorkerRequest) (*Worker, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_GetQueueInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueuedTaskInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchedulerServer).GetQueueInfo(m, &schedulerGetQueueInfoServer{stream})
}

type Scheduler_GetQueueInfoServer interface {
	Send(*QueuedTaskInfo) error
	grpc.ServerStream
}

type schedulerGetQueueInfoServer struct {
	grpc.ServerStream
}

func (x *schedulerGetQueueInfoServer) Send(m *QueuedTaskInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Scheduler_UpdateExecutorLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExecutorLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UpdateExecutorLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funnel.Scheduler/UpdateExecutorLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UpdateExecutorLogs(ctx, req.(*UpdateExecutorLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UpdateWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Worker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UpdateWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funnel.Scheduler/UpdateWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UpdateWorker(ctx, req.(*Worker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funnel.Scheduler/GetWorkers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetWorkers(ctx, req.(*GetWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funnel.Scheduler/GetWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetWorker(ctx, req.(*GetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "funnel.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateExecutorLogs",
			Handler:    _Scheduler_UpdateExecutorLogs_Handler,
		},
		{
			MethodName: "UpdateWorker",
			Handler:    _Scheduler_UpdateWorker_Handler,
		},
		{
			MethodName: "GetWorkers",
			Handler:    _Scheduler_GetWorkers_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _Scheduler_GetWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetQueueInfo",
			Handler:       _Scheduler_GetQueueInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "funnel.proto",
}

func init() { proto.RegisterFile("funnel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xd1, 0x6e, 0xe3, 0x44,
	0x14, 0xad, 0xe3, 0x24, 0x8d, 0x6f, 0xd2, 0xe0, 0xde, 0x2d, 0x95, 0xd7, 0xdb, 0x45, 0x5e, 0x3f,
	0x19, 0x84, 0x1a, 0x08, 0x3c, 0xac, 0x40, 0x5a, 0x81, 0x44, 0x55, 0x55, 0x62, 0xa5, 0xdd, 0x59,
	0xca, 0x3e, 0xa1, 0x68, 0x36, 0x9e, 0x4d, 0x47, 0x75, 0x66, 0x8c, 0x3d, 0x0e, 0xdd, 0x45, 0x48,
	0x88, 0x5f, 0xe0, 0x3b, 0xf8, 0x0f, 0xde, 0xf9, 0x05, 0x3e, 0x04, 0xcd, 0x8c, 0x9d, 0x3a, 0x4d,
	0xca, 0xdb, 0xf5, 0xbd, 0xe7, 0x9e, 0xb9, 0x73, 0xce, 0x9d, 0x04, 0x46, 0x6f, 0x2b, 0x21, 0x58,
	0x76, 0x9a, 0x17, 0x52, 0x49, 0xec, 0xdb, 0xaf, 0xd0, 0x53, 0xac, 0xb4, 0xa9, 0xf0, 0x64, 0x21,
	0xe5, 0x22, 0x63, 0x13, 0x9a, 0xf3, 0x09, 0x15, 0x42, 0x2a, 0xaa, 0xb8, 0x14, 0x75, 0x35, 0x3e,
	0x03, 0x8f, 0xb0, 0x52, 0x56, 0xc5, 0x9c, 0x95, 0x88, 0xd0, 0x9d, 0xe7, 0x55, 0x19, 0x38, 0x91,
	0x93, 0x1c, 0x10, 0x13, 0xa3, 0x0f, 0x6e, 0x41, 0x97, 0x41, 0x27, 0x72, 0x12, 0x87, 0xe8, 0x50,
	0xa3, 0x52, 0x5e, 0x5e, 0x07, 0xae, 0x49, 0x99, 0x38, 0xfe, 0xbb, 0x0b, 0xfd, 0xd7, 0xb2, 0xb8,
	0x66, 0x05, 0x8e, 0xa1, 0xc3, 0x53, 0x43, 0xe1, 0x91, 0x0e, 0x4f, 0x71, 0x02, 0x3d, 0x45, 0xcb,
	0xeb, 0x32, 0xe8, 0x44, 0x6e, 0x32, 0x9c, 0x3e, 0x3c, 0xad, 0x07, 0xb6, 0xf0, 0xd3, 0x1f, 0x74,
	0xed, 0x4c, 0xa8, 0xe2, 0x1d, 0xb1, 0x38, 0x9c, 0x80, 0x57, 0x34, 0x23, 0x05, 0xbd, 0xc8, 0x49,
	0x86, 0xd3, 0xc3, 0xa6, 0x69, 0x3d, 0x2b, 0xb9, 0xc5, 0xe8, 0x06, 0xba, 0xa2, 0x3c, 0xa3, 0x6f,
	0x32, 0x16, 0xf4, 0xef, 0x6d, 0x58, 0x63, 0xf0, 0x11, 0x78, 0x19, 0x2d, 0xd5, 0x2c, 0xe7, 0x62,
	0x11, 0xec, 0x47, 0x4e, 0xe2, 0x92, 0x81, 0x4e, 0xbc, 0xe0, 0x62, 0x81, 0x1f, 0x43, 0xaf, 0x54,
	0x54, 0xb1, 0x60, 0x10, 0x39, 0xc9, 0x78, 0xfa, 0x60, 0x73, 0xde, 0x57, 0xba, 0x44, 0x2c, 0x02,
	0x23, 0x18, 0xe6, 0x05, 0x63, 0xcb, 0x5c, 0x71, 0x7d, 0xb4, 0x17, 0x39, 0xc9, 0x80, 0xb4, 0x53,
	0xf8, 0x04, 0x46, 0x74, 0xae, 0xf8, 0x8a, 0xcd, 0x72, 0x59, 0xa8, 0x32, 0x80, 0xc8, 0x4d, 0x7a,
	0x64, 0x68, 0x73, 0x2f, 0x74, 0x4a, 0xcb, 0xf9, 0x5e, 0x0a, 0x16, 0x0c, 0x8d, 0x62, 0x26, 0xc6,
	0x10, 0x06, 0x57, 0xb2, 0x54, 0x82, 0x2e, 0x59, 0x70, 0x60, 0xf2, 0xeb, 0x6f, 0x0c, 0x60, 0x7f,
	0xc5, 0x8a, 0x92, 0x4b, 0x11, 0x8c, 0xcd, 0xe8, 0xcd, 0x27, 0x3e, 0x85, 0xc1, 0x92, 0x29, 0x9a,
	0x52, 0x45, 0x83, 0x0f, 0x8c, 0xd8, 0x27, 0x77, 0xc4, 0x7e, 0x5e, 0x97, 0xad, 0xde, 0x6b, 0x74,
	0xf8, 0x1c, 0xe0, 0xd6, 0x07, 0x6d, 0xf9, 0x35, 0x7b, 0x57, 0x5b, 0xa8, 0x43, 0xad, 0xc9, 0x8a,
	0x66, 0x15, 0x33, 0x6b, 0x30, 0xbc, 0xd5, 0x44, 0x37, 0xbd, 0x2e, 0x68, 0x9e, 0xb3, 0x82, 0x58,
	0xc4, 0x57, 0x9d, 0xa7, 0x4e, 0xf8, 0x35, 0x1c, 0x6c, 0x9c, 0xb4, 0x83, 0xf1, 0xa8, 0xcd, 0xe8,
	0xb5, 0x9a, 0xe3, 0x6f, 0x60, 0xd8, 0xa2, 0xc5, 0xc7, 0xd0, 0xd5, 0x6b, 0x61, 0x7a, 0x87, 0x53,
	0xef, 0x54, 0x2f, 0xb6, 0xae, 0x13, 0x93, 0xd6, 0xea, 0xd1, 0x4a, 0x5d, 0xd5, 0x34, 0x26, 0x8e,
	0x7f, 0x77, 0xe0, 0xe1, 0x65, 0x9e, 0x52, 0xc5, 0xce, 0x6e, 0xd8, 0xbc, 0x52, 0xb2, 0xf8, 0x5e,
	0x2e, 0x4a, 0xc2, 0x7e, 0xae, 0x58, 0xa9, 0xb6, 0xf6, 0x13, 0xa1, 0x5b, 0x2a, 0x96, 0x1b, 0x06,
	0x97, 0x98, 0x18, 0x63, 0x70, 0x33, 0xb9, 0x08, 0xba, 0xe6, 0x4c, 0xdf, 0x9c, 0xd9, 0xa2, 0x22,
	0xba, 0xa8, 0x97, 0xe8, 0x17, 0xa3, 0xea, 0x8c, 0xa7, 0x66, 0x4d, 0x3d, 0x32, 0xb0, 0x89, 0x8b,
	0x34, 0x3e, 0x81, 0x70, 0xd7, 0x04, 0x65, 0x2e, 0x45, 0xc9, 0xe2, 0x2f, 0xe1, 0xc3, 0x97, 0x15,
	0xab, 0x58, 0xaa, 0x2f, 0x72, 0x21, 0xde, 0xca, 0x66, 0xb6, 0x47, 0xe0, 0x2d, 0xe9, 0xcd, 0xcc,
	0xbe, 0x17, 0x3d, 0x62, 0x8f, 0x0c, 0x96, 0xf4, 0xc6, 0x78, 0x13, 0xff, 0x08, 0xe3, 0xcd, 0x2e,
	0x3c, 0x86, 0x3e, 0x17, 0x79, 0xa5, 0x34, 0xd6, 0x4d, 0x3c, 0x52, 0x7f, 0xe1, 0xa7, 0xed, 0x17,
	0x64, 0x2d, 0x1b, 0x9b, 0x4b, 0xec, 0x7a, 0x3e, 0xf1, 0x03, 0x38, 0x3c, 0x67, 0xca, 0x6e, 0x48,
	0xa3, 0x52, 0xfc, 0x0c, 0xb0, 0x9d, 0xb4, 0x83, 0x63, 0x02, 0xfb, 0xf6, 0x8a, 0xf6, 0x44, 0x4d,
	0xbb, 0xb1, 0x60, 0xa4, 0x29, 0xc7, 0xc7, 0x70, 0x64, 0x05, 0xa8, 0x0b, 0xcd, 0xd5, 0x63, 0xf0,
	0xd7, 0xbc, 0xf7, 0x38, 0xf2, 0xc9, 0x4b, 0x18, 0xb6, 0x1e, 0x1b, 0x1e, 0xc2, 0xc1, 0xa5, 0xe0,
	0x82, 0x2b, 0x4e, 0x33, 0xfe, 0x9e, 0xa5, 0xfe, 0x1e, 0x7a, 0xd0, 0xfb, 0x36, 0xe3, 0x2b, 0xe6,
	0x3b, 0x38, 0x80, 0xee, 0x77, 0x8c, 0xa6, 0x7e, 0x47, 0x47, 0xe7, 0x52, 0x30, 0xdf, 0x45, 0x1f,
	0x46, 0x17, 0x0d, 0x9e, 0x8b, 0x85, 0xdf, 0x9d, 0xfe, 0xe5, 0x82, 0xf7, 0x6a, 0x7e, 0xc5, 0xd2,
	0x2a, 0x63, 0x05, 0x5e, 0xc0, 0xe8, 0x9c, 0x29, 0x23, 0xa6, 0xd1, 0xf1, 0x71, 0x73, 0x8b, 0x9d,
	0xae, 0x84, 0xc7, 0xbb, 0xcb, 0xf1, 0xde, 0x67, 0x0e, 0xfe, 0x04, 0xb8, 0x6d, 0x34, 0x3e, 0x69,
	0x3a, 0xee, 0x5d, 0xc3, 0x30, 0xfe, 0x3f, 0x48, 0x2d, 0xd6, 0x1e, 0x3e, 0x83, 0x51, 0x5b, 0x46,
	0xbc, 0xa3, 0x77, 0x78, 0xb2, 0xc9, 0x72, 0x47, 0xec, 0x3d, 0x9c, 0x01, 0xdc, 0xda, 0x88, 0xeb,
	0xdf, 0xde, 0x2d, 0xbf, 0xc3, 0x70, 0x57, 0xa9, 0xa6, 0x09, 0xff, 0xf8, 0xe7, 0xdf, 0x3f, 0x3b,
	0x47, 0x88, 0x93, 0xd5, 0xe7, 0x13, 0x0b, 0x9b, 0xd4, 0x3e, 0xe3, 0x25, 0x78, 0xeb, 0x0e, 0x0c,
	0xb6, 0x48, 0x1a, 0xfa, 0x3b, 0x73, 0xc7, 0x1f, 0x19, 0xca, 0x00, 0x8f, 0xb7, 0x28, 0x27, 0xbf,
	0xf2, 0xf4, 0xb7, 0x37, 0x7d, 0xf3, 0xef, 0xf4, 0xc5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97,
	0xbe, 0xae, 0x2a, 0xde, 0x06, 0x00, 0x00,
}
