#!/usr/bin/env python

"""
Simple tool to allow for blocking during TES tasks
"""

import argparse
from flask import Flask, request

global wait_key
app = Flask(__name__)


def shutdown_server():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()


@app.route('/shutdown', methods=['POST', 'GET'])
def shutdown():
    shutdown_server()
    return ""


@app.route('/', methods=['GET'])
def index():
    return ' '.join(wait_key)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("wait_key", type=str, nargs='+')
    args = parser.parse_args()
    wait_key = args.wait_key
    app.run(host='0.0.0.0', port=5000)
