Compute: {{ .Values.Compute }}

Kubernetes:
  Executor: {{ .Values.Kubernetes.Executor }}
  DisableReconciler: {{ .Values.Kubernetes.DisableReconciler }}
  ReconcileRate: {{ .Values.Kubernetes.ReconcileRate }}
  Namespace: {{ .Release.Namespace }}
  JobsNamespace: {{ .Values.Kubernetes.JobsNamespace }}
  ServiceAccount: {{ .Values.Kubernetes.ServiceAccount }}
  Bucket: {{ .Values.Kubernetes.Bucket }}
  Region: {{ .Values.Kubernetes.Region }}

  # Worker Job
  Template: |
{{ default (.Files.Get "files/worker-job.yaml") .Values.Kubernetes.Template | indent 4 }}
  TemplateFile: {{ .Values.Kubernetes.TemplateFile }}

  # Executor Job
  ExecutorTemplate: |
{{ default (.Files.Get "files/executor-job.yaml") .Values.Kubernetes.ExecutorTemplate | indent 4 }}
  ExecutorTemplateFile: {{ .Values.Kubernetes.ExecutorTemplateFile }}

Database: {{ .Values.Database }}

EventWriters:
  {{- range .Values.EventWriters }}
  - {{ . }}
  {{- end }}

Logger:
  Level: {{ .Values.Logger.Level }}
  OutputFile: {{ .Values.Logger.OutputFile }}

Server:
  HostName: {{ .Values.Server.HostName }}
  HTTPPort: {{ .Values.Server.HttpPort }}
  RPCPort: {{ .Values.Server.RpcPort }}
  DisableHTTPCache: {{ .Values.Server.DisableHttpCache }}

RPCClient:
  ServerAddress: {{ .Values.RPCClient.ServerAddress }}
  Timeout: {{ .Values.RPCClient.Timeout }}
  MaxRetries: {{ .Values.RPCClient.MaxRetries }}

Scheduler:
  ScheduleRate: {{ .Values.Scheduler.ScheduleRate }}
  ScheduleChunk: {{ .Values.Scheduler.ScheduleChunk }}
  NodePingTimeout: {{ .Values.Scheduler.NodePingTimeout }}
  NodeInitTimeout: {{ .Values.Scheduler.NodeInitTimeout }}

Node:
  ID: {{ .Values.Node.Id }}
  Timeout: {{ .Values.Node.Timeout }}
  UpdateRate: {{ .Values.Node.UpdateRate }}
  Resources:
    Cpus: {{ .Values.Node.Resources.cpus }}
    RamGb: {{ .Values.Node.Resources.ramGb }}
    DiskGb: {{ .Values.Node.Resources.diskGb }}

Worker:
  WorkDir: {{ .Values.Worker.WorkDir }}
  PollingRate: {{ .Values.Worker.PollingRate }}
  LogUpdateRate: {{ .Values.Worker.LogUpdateRate }}
  LogTailSize: {{ .Values.Worker.LogTailSize }}
  LeaveWorkDir: {{ .Values.Worker.LeaveWorkDir }}
  MaxParallelTransfers: {{ .Values.Worker.MaxParallelTransfers }}

BoltDB:
  Path: {{ .Values.BoltDB.Path }}

AmazonS3:
  Disabled: {{ .Values.AmazonS3.Disabled }}
  MaxRetries: {{ .Values.AmazonS3.MaxRetries }}
  Key: {{ .Values.AmazonS3.Key }}
  Secret: {{ .Values.AmazonS3.Secret }}
  SSE:
    CustomerKeyFile: {{ .Values.AmazonS3.SSE.CustomerKeyFile }}
    KMSKey: {{ .Values.AmazonS3.SSE.KMSKey }}

DynamoDB:
  TableBasename: {{ .Values.DynamoDB.TableBasename }}
  Region: {{ .Values.DynamoDB.Region }}
  Key: {{ .Values.DynamoDB.Key }}
  Secret: {{ .Values.DynamoDB.Secret }}

Elastic:
  IndexPrefix: {{ .Values.Elastic.IndexPrefix }}
  URL: {{ .Values.Elastic.Url }}

Datastore:
  Project: {{ .Values.Datastore.Project }}
  CredentialsFile: {{ .Values.Datastore.CredentialsFile }}

MongoDB:
  Addrs:
    {{- if .Values.MongoDB.Addrs }}
      {{- range .Values.MongoDB.Addrs }}
    - {{ . }}
      {{- end }}
    {{- else }}
    - {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
  Database: {{ .Values.MongoDB.Database }}
  Timeout: {{ .Values.MongoDB.Timeout }}
  Username: {{ .Values.MongoDB.Username }}
  Password: {{ .Values.MongoDB.Password }}

Kafka:
  Servers:
  {{- range .Values.Kafka.Servers }}
  - {{ . }}
  {{- end }}
  Topic: {{ .Values.Kafka.Topic }}

Plugins:
  Disabled: {{ .Values.Plugins.Disabled }}
  Dir: {{ .Values.Plugins.Dir }}
  Plugin: {{ .Values.Plugins.Plugin }}
  Host: {{ .Values.Plugins.Host }}
  Input: {{ .Values.Plugins.Input }}
  JsonConfig: {{ .Values.Plugins.JsonConfig | quote }}
