Compute: {{ .Values.Compute }}

Kubernetes:
  Executor: {{ .Values.Kubernetes.Executor }}
  DisableReconciler: {{ .Values.Kubernetes.DisableReconciler }}
  ReconcileRate: {{ .Values.Kubernetes.ReconcileRate }}
  Namespace: {{ .Release.Namespace }}
  JobsNamespace: {{ .Values.Kubernetes.JobsNamespace }}
  ServiceAccount: {{ .Values.Kubernetes.ServiceAccount }}

  # Worker Job
  WorkerTemplate: |
{{ default (.Files.Get "files/worker-job.yaml") .Values.Kubernetes.WorkerTemplate | indent 4 }}

  # Executor Job
  ExecutorTemplate: |
{{ default (.Files.Get "files/executor-job.yaml") .Values.Kubernetes.ExecutorTemplate | indent 4 }}

  # PV template
  PVTemplate: |
{{ default (.Files.Get "files/worker-pv.yaml") .Values.Kubernetes.PVTemplate | indent 4 }}

  # PVC template
  PVCTemplate: |
{{ default (.Files.Get "files/worker-pvc.yaml") .Values.Kubernetes.PVCTemplate | indent 4 }}


Database: {{ .Values.Database }}

EventWriters:
  {{- range .Values.EventWriters }}
  - {{ . }}
  {{- end }}

Logger:
  level: {{ .Values.Logger.level }}
  outputFile: {{ .Values.Logger.outputFile }}

Server:
  HostName: {{ .Values.Server.HostName }}
  HTTPPort: {{ .Values.Server.HTTPPort }}
  RPCPort: {{ .Values.Server.RPCPort }}
  DisableHTTPCache: {{ .Values.Server.DisableHttpCache }}

RPCClient:
  ServerAddress: {{ .Values.RPCClient.ServerAddress }}
  Timeout:
    duration: {{ .Values.RPCClient.Timeout.duration }}
  MaxRetries: {{ .Values.RPCClient.MaxRetries }}

Scheduler:
  ScheduleRate: {{ .Values.Scheduler.ScheduleRate }}
  ScheduleChunk: {{ .Values.Scheduler.ScheduleChunk }}
  NodePingTimeout:
    duration: {{ .Values.Scheduler.NodePingTimeout.duration }}
  NodeInitTimeout:
    duration: {{ .Values.Scheduler.NodeInitTimeout.duration }}

Node:
  ID: {{ .Values.Node.Id }}
  Timeout:
    disabled: {{ .Values.Node.Timeout.disabled }}
  UpdateRate: {{ .Values.Node.UpdateRate }}
  Resources:
    Cpus: {{ .Values.Node.Resources.cpus }}
    RamGb: {{ .Values.Node.Resources.ramGb }}
    DiskGb: {{ .Values.Node.Resources.diskGb }}

Worker:
  WorkDir: {{ .Values.Worker.WorkDir }}
  PollingRate: {{ .Values.Worker.PollingRate }}
  LogUpdateRate: {{ .Values.Worker.LogUpdateRate }}
  LogTailSize: {{ .Values.Worker.LogTailSize }}
  LeaveWorkDir: {{ .Values.Worker.LeaveWorkDir }}
  MaxParallelTransfers: {{ .Values.Worker.MaxParallelTransfers }}

BoltDB:
  Path: {{ .Values.BoltDB.Path }}

AmazonS3:
  Disabled: {{ .Values.AmazonS3.Disabled }}
  AWSConfig:
    MaxRetries: {{ .Values.AmazonS3.AWSConfig.MaxRetries }}
    Key: {{ .Values.AmazonS3.AWSConfig.Key }}
    Secret: {{ .Values.AmazonS3.AWSConfig.Secret }}
  SSE:
    CustomerKeyFile: {{ .Values.AmazonS3.SSE.CustomerKeyFile }}
    KMSKey: {{ .Values.AmazonS3.SSE.KMSKey }}

DynamoDB:
  TableBasename: {{ .Values.DynamoDB.TableBasename }}
  AWSConfig:
    Region: {{ .Values.DynamoDB.AWSConfig.Region }}
    Key: {{ .Values.DynamoDB.AWSConfig.Key }}
    Secret: {{ .Values.DynamoDB.AWSConfig.Secret }}

Elastic:
  IndexPrefix: {{ .Values.Elastic.IndexPrefix }}
  URL: {{ .Values.Elastic.Url }}

Datastore:
  Project: {{ .Values.Datastore.Project }}
  CredentialsFile: {{ .Values.Datastore.CredentialsFile }}

MongoDB:
  Addrs:
    {{- if .Values.MongoDB.Addrs }}
      {{- range .Values.MongoDB.Addrs }}
    - {{ . }}
      {{- end }}
    {{- else }}
    - {{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
  Database: {{ .Values.MongoDB.Database }}
  Timeout:
    duration: {{ .Values.MongoDB.Timeout.duration }}
  Username: {{ .Values.MongoDB.Username }}
  Password: {{ .Values.MongoDB.Password }}

Kafka:
  Servers:
  {{- if .Values.Kafka.Servers }}
  {{- range .Values.Kafka.Servers }}
  - {{ . }}
  {{- end }}
  {{- else }}
  - ""
  {{- end }}
  Topic: {{ .Values.Kafka.Topic }}

GenericS3:
  {{- range .Values.GenericS3 }}
  - Disabled: {{ .Disabled }}
    Endpoint: {{ .Endpoint }}
    Key: {{ .Key }}
    Secret: {{ .Secret }}
    Bucket: {{ .Bucket }}
    Region: {{ .Region }}
  {{- end }}

Plugins:
  Path: {{ .Values.Plugins.Path }}
  Params:
  {{- if .Values.Plugins.Params }}
  {{- range $key, $value := .Values.Plugins.Params }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
