# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from events import events_pb2 as events_dot_events__pb2


class EventServiceStub(object):
    """*
    Event Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteEvent = channel.unary_unary(
                '/events.EventService/WriteEvent',
                request_serializer=events_dot_events__pb2.Event.SerializeToString,
                response_deserializer=events_dot_events__pb2.WriteEventResponse.FromString,
                )


class EventServiceServicer(object):
    """*
    Event Service
    """

    def WriteEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteEvent,
                    request_deserializer=events_dot_events__pb2.Event.FromString,
                    response_serializer=events_dot_events__pb2.WriteEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'events.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """*
    Event Service
    """

    @staticmethod
    def WriteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/events.EventService/WriteEvent',
            events_dot_events__pb2.Event.SerializeToString,
            events_dot_events__pb2.WriteEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
