Database: {{ .Values.Database }}

Compute: {{ .Values.Compute }}

Kubernetes:
  Executor: {{ .Values.Kubernetes.Executor }}
  Namespace: {{ .Release.Namespace }}
  DisableReconciler: {{ .Values.Kubernetes.DisableReconciler }}
  ReconcileRate: {{ .Values.Kubernetes.ReconcileRate }}
  ServiceAccount: {{ .Values.Kubernetes.ServiceAccount }}
  Template: {{ .Values.Kubernetes.Template }}
  TemplateFile: {{ .Values.Kubernetes.TemplateFile }}
  Bucket: {{ .Values.Kubernetes.Bucket }}
  Region: {{ .Values.Kubernetes.Region }}

Logger:
  Level: {{ .Values.Logger.level }}

RPCClient:
  MaxRetries: {{ .Values.RPCClient.maxRetries }}
  Timeout: {{ .Values.RPCClient.timeout }}

EventWriters:
  {{- range .Values.EventWriters }}
  - {{ . }}
  {{- end }}

AmazonS3:
  Disabled: {{ .Values.AmazonS3.Disabled }}
  MaxRetries: {{ .Values.AmazonS3.MaxRetries }}
  Key: {{ .Values.AmazonS3.Key }}
  Secret: {{ .Values.AmazonS3.Secret }}

Server:
  HostName: funnel.{{ .Release.Namespace }}.svc.cluster.local
  RPCPort: {{ .Values.Server.RPCPort }}

Worker:
  WorkDir: {{ .Values.Worker.WorkDir }}
  PollingRate: {{ .Values.Worker.PollingRate }}
  LogUpdateRate: {{ .Values.Worker.LogUpdateRate }}
  LogTailSize: {{ .Values.Worker.LogTailSize }}
  LeaveWorkDir: {{ .Values.Worker.LeaveWorkDir }}
  MaxParallelTransfers: {{ .Values.Worker.MaxParallelTransfers }}
