Compute: {{ .Values.Compute }}

Kubernetes:
  Executor: {{ .Values.Kubernetes.Executor }}
  Namespace: {{ .Release.Namespace }}
  DisableReconciler: {{ .Values.Kubernetes.DisableReconciler }}
  ReconcileRate: {{ .Values.Kubernetes.ReconcileRate }}
  ServiceAccount: {{ .Values.Kubernetes.ServiceAccount }}
  Template: {{ .Values.Kubernetes.Template }}
  TemplateFile: {{ .Values.Kubernetes.TemplateFile }}
  Bucket: {{ .Values.Kubernetes.Bucket }}
  Region: {{ .Values.Kubernetes.Region }}

Database: {{ .Values.Database }}

EventWriters:
  {{- range .Values.EventWriters }}
  - {{ . }}
  {{- end }}

Logger:
  Level: {{ .Values.Logger.Level }}
  OutputFile: {{ .Values.Logger.OutputFile }}

Server:
  HostName: {{ .Values.Server.Hostname }}
  HTTPPort: {{ .Values.Server.HttpPort }}
  RPCPort: {{ .Values.Server.RpcPort }}
  DisableHTTPCache: {{ .Values.Server.DisableHttpCache }}

RPCClient:
  ServerAddress: {{ .Values.RPCClient.ServerAddress }}
  Timeout: {{ .Values.RPCClient.Timeout }}
  MaxRetries: {{ .Values.RPCClient.MaxRetries }}

Scheduler:
  ScheduleRate: {{ .Values.Scheduler.ScheduleRate }}
  ScheduleChunk: {{ .Values.Scheduler.ScheduleChunk }}
  NodePingTimeout: {{ .Values.Scheduler.NodePingTimeout }}
  NodeInitTimeout: {{ .Values.Scheduler.NodeInitTimeout }}

Node:
  ID: {{ .Values.Node.Id }}
  Timeout: {{ .Values.Node.Timeout }}
  UpdateRate: {{ .Values.Node.UpdateRate }}
  Resources:
    Cpus: {{ .Values.Node.Resources.cpus }}
    RamGb: {{ .Values.Node.Resources.ramGb }}
    DiskGb: {{ .Values.Node.Resources.diskGb }}

Worker:
  WorkDir: {{ .Values.Worker.WorkDir }}
  PollingRate: {{ .Values.Worker.PollingRate }}
  LogUpdateRate: {{ .Values.Worker.LogUpdateRate }}
  LogTailSize: {{ .Values.Worker.LogTailSize }}
  LeaveWorkDir: {{ .Values.Worker.LeaveWorkDir }}
  MaxParallelTransfers: {{ .Values.Worker.MaxParallelTransfers }}

BoltDB:
  Path: {{ .Values.BoltDB.Path }}

AmazonS3:
  Disabled: {{ .Values.AmazonS3.Disabled }}
  MaxRetries: {{ .Values.AmazonS3.MaxRetries }}
  Key: {{ .Values.AmazonS3.Key }}
  Secret: {{ .Values.AmazonS3.Secret }}

DynamoDB:
  TableBasename: {{ .Values.DynamoDB.TableBasename }}
  Region: {{ .Values.DynamoDB.Region }}
  Key: {{ .Values.DynamoDB.Key }}
  Secret: {{ .Values.DynamoDB.Secret }}

Elastic:
  IndexPrefix: {{ .Values.Elastic.IndexPrefix }}
  URL: {{ .Values.Elastic.Url }}

Datastore:
  Project: {{ .Values.Datastore.Project }}
  CredentialsFile: {{ .Values.Datastore.CredentialsFile }}

MongoDB:
  Addrs:
  {{- range .Values.MongoDB.Addrs }}
  - {{ . }}
  {{- end }}
  Database: {{ .Values.MongoDB.Database }}
  Timeout: {{ .Values.MongoDB.Timeout }}
  Username: {{ .Values.MongoDB.Username }}
  Password: {{ .Values.MongoDB.Password }}

Kafka:
  Servers:
  {{- range .Values.Kafka.Servers }}
  - {{ . }}
  {{- end }}
  Topic: {{ .Values.Kafka.Topic }}
