// Code generated by protoc-gen-go.
// source: task_execution.proto
// DO NOT EDIT!

/*
Package ga4gh_task_exec is a generated protocol buffer package.

It is generated from these files:
	task_execution.proto

It has these top-level messages:
	TaskParameter
	PortMapping
	DockerExecutor
	Volume
	Resources
	Task
	JobListRequest
	TaskDesc
	JobDesc
	JobListResponse
	JobID
	JobLog
	Job
	ServiceInfoRequest
	ServiceInfo
*/
package ga4gh_task_exec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_Unknown     State = 0
	State_Queued      State = 1
	State_Running     State = 2
	State_Paused      State = 3
	State_Complete    State = 4
	State_Error       State = 5
	State_SystemError State = 6
	State_Canceled    State = 7
)

var State_name = map[int32]string{
	0: "Unknown",
	1: "Queued",
	2: "Running",
	3: "Paused",
	4: "Complete",
	5: "Error",
	6: "SystemError",
	7: "Canceled",
}
var State_value = map[string]int32{
	"Unknown":     0,
	"Queued":      1,
	"Running":     2,
	"Paused":      3,
	"Complete":    4,
	"Error":       5,
	"SystemError": 6,
	"Canceled":    7,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Parameters for Task
type TaskParameter struct {
	// OPTIONAL
	// name of the parameter
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// OPTIONAL
	// Text description
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// REQUIRED
	// location in long term storage, is a url specific to the implementing
	// system. For example s3://my-object-store/file1 or gs://my-bucket/file2 or
	// file:///path/to/my/file
	Location string `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	// REQUIRED
	// path in the machine file system. Note, this MUST be a path that exists
	// within one of the defined volumes
	// If the file is mounted in a volume that is mounted read/write the file must
	// be accessable to processes in the container. Optimizations, suc as hard linking
	// to a source file, or providing a streaming input from a FUSE mount should only
	// be done if the volume is mounted as read only
	Path string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	// REQUIRED
	// Type of data, "File" or "Directory"
	// if used for an output all the files in the directory
	// will be copied to the storage location
	Class string `protobuf:"bytes,5,opt,name=class" json:"class,omitempty"`
	// OPTIONAL: default false
	// if the parameter is an output, should the element be created before executing
	// the command. For example if saving the working directory as an output,
	// the directory needs to exist before the command is called. If false, it is
	// assumed that the user will create the element as a part of the operation
	Create bool `protobuf:"varint,6,opt,name=create" json:"create,omitempty"`
}

func (m *TaskParameter) Reset()                    { *m = TaskParameter{} }
func (m *TaskParameter) String() string            { return proto.CompactTextString(m) }
func (*TaskParameter) ProtoMessage()               {}
func (*TaskParameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TaskParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskParameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TaskParameter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *TaskParameter) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TaskParameter) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *TaskParameter) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

// host to container port mappings
type PortMapping struct {
	// REQUIRED
	// Exposed port on container
	ContainerPort int32 `protobuf:"varint,1,opt,name=containerPort" json:"containerPort,omitempty"`
	// REQUIRED
	// Must be greater than 1024;
	// Use 0 to have host find an open port;
	// Docker cmd will fail if this port is already allocated on the worker
	HostBinding int32 `protobuf:"varint,2,opt,name=hostBinding" json:"hostBinding,omitempty"`
}

func (m *PortMapping) Reset()                    { *m = PortMapping{} }
func (m *PortMapping) String() string            { return proto.CompactTextString(m) }
func (*PortMapping) ProtoMessage()               {}
func (*PortMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PortMapping) GetContainerPort() int32 {
	if m != nil {
		return m.ContainerPort
	}
	return 0
}

func (m *PortMapping) GetHostBinding() int32 {
	if m != nil {
		return m.HostBinding
	}
	return 0
}

// A command line to be executed and the docker container to run it
type DockerExecutor struct {
	// REQUIRED
	// Docker Image name
	ImageName string `protobuf:"bytes,1,opt,name=imageName" json:"imageName,omitempty"`
	// REQUIRED
	// The command to be executed
	Cmd []string `protobuf:"bytes,2,rep,name=cmd" json:"cmd,omitempty"`
	// OPTIONAL: default docker image directory
	// The working directory that the command will be executed in
	Workdir string `protobuf:"bytes,3,opt,name=workdir" json:"workdir,omitempty"`
	// OPTIONAL
	// Path for supplying input to stdin, blank if none
	Stdin string `protobuf:"bytes,6,opt,name=stdin" json:"stdin,omitempty"`
	// OPTIONAL
	// Path for stdout recording, blank if not storing to file
	Stdout string `protobuf:"bytes,4,opt,name=stdout" json:"stdout,omitempty"`
	// OPTIONAL
	// Path for stderr recording, blank if not storing to file
	Stderr string `protobuf:"bytes,5,opt,name=stderr" json:"stderr,omitempty"`
	// OPTIONAL
	// Port to expose from within the container, blank if none
	PortBindings []*PortMapping `protobuf:"bytes,7,rep,name=portBindings" json:"portBindings,omitempty"`
}

func (m *DockerExecutor) Reset()                    { *m = DockerExecutor{} }
func (m *DockerExecutor) String() string            { return proto.CompactTextString(m) }
func (*DockerExecutor) ProtoMessage()               {}
func (*DockerExecutor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DockerExecutor) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *DockerExecutor) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *DockerExecutor) GetWorkdir() string {
	if m != nil {
		return m.Workdir
	}
	return ""
}

func (m *DockerExecutor) GetStdin() string {
	if m != nil {
		return m.Stdin
	}
	return ""
}

func (m *DockerExecutor) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *DockerExecutor) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *DockerExecutor) GetPortBindings() []*PortMapping {
	if m != nil {
		return m.PortBindings
	}
	return nil
}

// Attached volume request.
type Volume struct {
	// OPTIONAL
	// Name of attached volume
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// REQUIRED
	// Minimum size
	SizeGb float64 `protobuf:"fixed64,2,opt,name=sizeGb" json:"sizeGb,omitempty"`
	// OPTIONAL
	// Source volume, this would refer to an existing volume the execution engine
	// could identify. Leave blank if is to be a newly created volume
	// Volumes loaded from a source will be mounted as read only
	Source string `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	// REQUIRED
	// mount point for volume inside the docker container
	MountPoint string `protobuf:"bytes,6,opt,name=mountPoint" json:"mountPoint,omitempty"`
	// OPTIONAL default False
	Readonly bool `protobuf:"varint,7,opt,name=readonly" json:"readonly,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetSizeGb() float64 {
	if m != nil {
		return m.SizeGb
	}
	return 0
}

func (m *Volume) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Volume) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

func (m *Volume) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type Resources struct {
	// OPTIONAL default 1
	// Minimum number of CPUs
	MinimumCpuCores uint32 `protobuf:"varint,1,opt,name=minimumCpuCores" json:"minimumCpuCores,omitempty"`
	// Can schedule on resource that resource that can be preempted, like AWS Spot Instances
	// OPTIONAL default false
	Preemptible bool `protobuf:"varint,2,opt,name=preemptible" json:"preemptible,omitempty"`
	// REQUIRED
	// Minimum RAM required
	MinimumRamGb float64 `protobuf:"fixed64,3,opt,name=minimumRamGb" json:"minimumRamGb,omitempty"`
	// REQUIRED
	// Volumes to be mounted into the docker container
	Volumes []*Volume `protobuf:"bytes,4,rep,name=volumes" json:"volumes,omitempty"`
	// OPTIONAL
	// optional scheduling information for systems where multiple compute zones are avalible
	Zones []string `protobuf:"bytes,5,rep,name=zones" json:"zones,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Resources) GetMinimumCpuCores() uint32 {
	if m != nil {
		return m.MinimumCpuCores
	}
	return 0
}

func (m *Resources) GetPreemptible() bool {
	if m != nil {
		return m.Preemptible
	}
	return false
}

func (m *Resources) GetMinimumRamGb() float64 {
	if m != nil {
		return m.MinimumRamGb
	}
	return 0
}

func (m *Resources) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *Resources) GetZones() []string {
	if m != nil {
		return m.Zones
	}
	return nil
}

// The description of a task to be run
type Task struct {
	// OPTIONAL
	// user name for task
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// OPTIONAL
	// parameter for execution engine to define/store group information
	ProjectID string `protobuf:"bytes,2,opt,name=projectID" json:"projectID,omitempty"`
	// OPTIONAL
	// free text description of task
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// REQUIRED
	// Files to be copied into system before tasks
	Inputs []*TaskParameter `protobuf:"bytes,4,rep,name=inputs" json:"inputs,omitempty"`
	// REQUIRED
	// Files to be copied out of the system after tasks
	Outputs []*TaskParameter `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	// REQUIRED
	// Define required system resources to run job
	Resources *Resources `protobuf:"bytes,6,opt,name=resources" json:"resources,omitempty"`
	// REQUIRED
	// An array of docker executions that will be run sequentially
	Docker []*DockerExecutor `protobuf:"bytes,8,rep,name=docker" json:"docker,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetInputs() []*TaskParameter {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Task) GetOutputs() []*TaskParameter {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Task) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Task) GetDocker() []*DockerExecutor {
	if m != nil {
		return m.Docker
	}
	return nil
}

// Request listing of jobs tracked by server
type JobListRequest struct {
	// OPTIONAL
	// The name of the project to search for pipelines. Caller must have READ access to this project.
	ProjectID string `protobuf:"bytes,1,opt,name=projectID" json:"projectID,omitempty"`
	// OPTIONAL
	// Pipelines with names that match this prefix should be returned. If unspecified, all pipelines in the project, up to pageSize, will be returned.
	NamePrefix string `protobuf:"bytes,2,opt,name=namePrefix" json:"namePrefix,omitempty"`
	// OPTIONAL
	// Number of pipelines to return at once. Defaults to 256, and max is 2048.
	PageSize uint32 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	// OPTIONAL
	// Token to use to indicate where to start getting results. If unspecified, returns the first page of results.
	PageToken string `protobuf:"bytes,4,opt,name=pageToken" json:"pageToken,omitempty"`
}

func (m *JobListRequest) Reset()                    { *m = JobListRequest{} }
func (m *JobListRequest) String() string            { return proto.CompactTextString(m) }
func (*JobListRequest) ProtoMessage()               {}
func (*JobListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *JobListRequest) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *JobListRequest) GetNamePrefix() string {
	if m != nil {
		return m.NamePrefix
	}
	return ""
}

func (m *JobListRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *JobListRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// Small description of tasks, returned by server during listing
type TaskDesc struct {
	// OPTIONAL
	// user name for task
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// OPTIONAL
	// parameter for execution engine to define/store group information
	ProjectID string `protobuf:"bytes,2,opt,name=projectID" json:"projectID,omitempty"`
	// OPTIONAL
	// free text description of task
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *TaskDesc) Reset()                    { *m = TaskDesc{} }
func (m *TaskDesc) String() string            { return proto.CompactTextString(m) }
func (*TaskDesc) ProtoMessage()               {}
func (*TaskDesc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TaskDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskDesc) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *TaskDesc) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Small description of jobs, returned by server during listing
type JobDesc struct {
	// REQUIRED
	JobID string `protobuf:"bytes,1,opt,name=jobID" json:"jobID,omitempty"`
	// REQUIRED
	State State `protobuf:"varint,2,opt,name=state,enum=ga4gh_task_exec.State" json:"state,omitempty"`
	// REQUIRED short description of task
	Task *TaskDesc `protobuf:"bytes,3,opt,name=task" json:"task,omitempty"`
}

func (m *JobDesc) Reset()                    { *m = JobDesc{} }
func (m *JobDesc) String() string            { return proto.CompactTextString(m) }
func (*JobDesc) ProtoMessage()               {}
func (*JobDesc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *JobDesc) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *JobDesc) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Unknown
}

func (m *JobDesc) GetTask() *TaskDesc {
	if m != nil {
		return m.Task
	}
	return nil
}

// Return envelope
type JobListResponse struct {
	Jobs          []*JobDesc `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
	NextPageToken string     `protobuf:"bytes,2,opt,name=nextPageToken" json:"nextPageToken,omitempty"`
}

func (m *JobListResponse) Reset()                    { *m = JobListResponse{} }
func (m *JobListResponse) String() string            { return proto.CompactTextString(m) }
func (*JobListResponse) ProtoMessage()               {}
func (*JobListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *JobListResponse) GetJobs() []*JobDesc {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *JobListResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// ID of an instance of a Task
type JobID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *JobID) Reset()                    { *m = JobID{} }
func (m *JobID) String() string            { return proto.CompactTextString(m) }
func (*JobID) ProtoMessage()               {}
func (*JobID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *JobID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type JobLog struct {
	// The command line that was run
	Cmd []string `protobuf:"bytes,1,rep,name=cmd" json:"cmd,omitempty"`
	// When the command was executed
	StartTime string `protobuf:"bytes,2,opt,name=startTime" json:"startTime,omitempty"`
	// When the command completed
	EndTime string `protobuf:"bytes,3,opt,name=endTime" json:"endTime,omitempty"`
	// Sample of stdout (not guaranteed to be entire log)
	Stdout string `protobuf:"bytes,4,opt,name=stdout" json:"stdout,omitempty"`
	// Sample of stderr (not guaranteed to be entire log)
	Stderr string `protobuf:"bytes,5,opt,name=stderr" json:"stderr,omitempty"`
	// Exit code of the program
	ExitCode int32 `protobuf:"varint,6,opt,name=exitCode" json:"exitCode,omitempty"`
	// ip of worker host
	HostIP string `protobuf:"bytes,7,opt,name=hostIP" json:"hostIP,omitempty"`
	// port bound from container to host
	PortBindings []*PortMapping `protobuf:"bytes,8,rep,name=portBindings" json:"portBindings,omitempty"`
}

func (m *JobLog) Reset()                    { *m = JobLog{} }
func (m *JobLog) String() string            { return proto.CompactTextString(m) }
func (*JobLog) ProtoMessage()               {}
func (*JobLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *JobLog) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *JobLog) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *JobLog) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *JobLog) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *JobLog) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *JobLog) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *JobLog) GetHostIP() string {
	if m != nil {
		return m.HostIP
	}
	return ""
}

func (m *JobLog) GetPortBindings() []*PortMapping {
	if m != nil {
		return m.PortBindings
	}
	return nil
}

// The description of the running instance of a task
type Job struct {
	JobID    string            `protobuf:"bytes,1,opt,name=jobID" json:"jobID,omitempty"`
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Task     *Task             `protobuf:"bytes,3,opt,name=task" json:"task,omitempty"`
	State    State             `protobuf:"varint,4,opt,name=state,enum=ga4gh_task_exec.State" json:"state,omitempty"`
	Logs     []*JobLog         `protobuf:"bytes,5,rep,name=logs" json:"logs,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Job) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *Job) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Job) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Job) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Unknown
}

func (m *Job) GetLogs() []*JobLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

// Blank request message for service request
type ServiceInfoRequest struct {
}

func (m *ServiceInfoRequest) Reset()                    { *m = ServiceInfoRequest{} }
func (m *ServiceInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceInfoRequest) ProtoMessage()               {}
func (*ServiceInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// Information about Task Execution Service
// May include information related (but not limited to)
// resource availability and storage system information
type ServiceInfo struct {
	// System specific key/value pairs
	// Example for a shared file system based storage system:
	// storageType=sharedFile, baseDir=/path/to/shared/directory
	StorageConfig map[string]string `protobuf:"bytes,1,rep,name=storageConfig" json:"storageConfig,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServiceInfo) Reset()                    { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string            { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()               {}
func (*ServiceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ServiceInfo) GetStorageConfig() map[string]string {
	if m != nil {
		return m.StorageConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskParameter)(nil), "ga4gh_task_exec.TaskParameter")
	proto.RegisterType((*PortMapping)(nil), "ga4gh_task_exec.PortMapping")
	proto.RegisterType((*DockerExecutor)(nil), "ga4gh_task_exec.DockerExecutor")
	proto.RegisterType((*Volume)(nil), "ga4gh_task_exec.Volume")
	proto.RegisterType((*Resources)(nil), "ga4gh_task_exec.Resources")
	proto.RegisterType((*Task)(nil), "ga4gh_task_exec.Task")
	proto.RegisterType((*JobListRequest)(nil), "ga4gh_task_exec.JobListRequest")
	proto.RegisterType((*TaskDesc)(nil), "ga4gh_task_exec.TaskDesc")
	proto.RegisterType((*JobDesc)(nil), "ga4gh_task_exec.JobDesc")
	proto.RegisterType((*JobListResponse)(nil), "ga4gh_task_exec.JobListResponse")
	proto.RegisterType((*JobID)(nil), "ga4gh_task_exec.JobID")
	proto.RegisterType((*JobLog)(nil), "ga4gh_task_exec.JobLog")
	proto.RegisterType((*Job)(nil), "ga4gh_task_exec.Job")
	proto.RegisterType((*ServiceInfoRequest)(nil), "ga4gh_task_exec.ServiceInfoRequest")
	proto.RegisterType((*ServiceInfo)(nil), "ga4gh_task_exec.ServiceInfo")
	proto.RegisterEnum("ga4gh_task_exec.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	// Get Service Info
	GetServiceInfo(ctx context.Context, in *ServiceInfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error)
	// Run a task
	RunTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*JobID, error)
	// List the TaskOps
	ListJobs(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	// Get info about a running task
	GetJob(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*Job, error)
	// Cancel a running task
	CancelJob(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*JobID, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetServiceInfo(ctx context.Context, in *ServiceInfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error) {
	out := new(ServiceInfo)
	err := grpc.Invoke(ctx, "/ga4gh_task_exec.TaskService/GetServiceInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RunTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*JobID, error) {
	out := new(JobID)
	err := grpc.Invoke(ctx, "/ga4gh_task_exec.TaskService/RunTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListJobs(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	out := new(JobListResponse)
	err := grpc.Invoke(ctx, "/ga4gh_task_exec.TaskService/ListJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetJob(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := grpc.Invoke(ctx, "/ga4gh_task_exec.TaskService/GetJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CancelJob(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*JobID, error) {
	out := new(JobID)
	err := grpc.Invoke(ctx, "/ga4gh_task_exec.TaskService/CancelJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	// Get Service Info
	GetServiceInfo(context.Context, *ServiceInfoRequest) (*ServiceInfo, error)
	// Run a task
	RunTask(context.Context, *Task) (*JobID, error)
	// List the TaskOps
	ListJobs(context.Context, *JobListRequest) (*JobListResponse, error)
	// Get info about a running task
	GetJob(context.Context, *JobID) (*Job, error)
	// Cancel a running task
	CancelJob(context.Context, *JobID) (*JobID, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ga4gh_task_exec.TaskService/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetServiceInfo(ctx, req.(*ServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ga4gh_task_exec.TaskService/RunTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RunTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ga4gh_task_exec.TaskService/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListJobs(ctx, req.(*JobListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ga4gh_task_exec.TaskService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetJob(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ga4gh_task_exec.TaskService/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CancelJob(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ga4gh_task_exec.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _TaskService_GetServiceInfo_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _TaskService_RunTask_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _TaskService_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _TaskService_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _TaskService_CancelJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_execution.proto",
}

func init() { proto.RegisterFile("task_execution.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0x66, 0xf6, 0x7f, 0x6b, 0xb3, 0xf6, 0xaa, 0x31, 0xc9, 0xb0, 0x32, 0x89, 0x35, 0x70, 0x30,
	0x21, 0xb1, 0x15, 0x83, 0x20, 0x0a, 0x12, 0x8a, 0xb0, 0x23, 0xcb, 0x56, 0x82, 0x96, 0x76, 0xcc,
	0x91, 0xa8, 0x77, 0xa6, 0x32, 0xe9, 0xec, 0x4e, 0xf7, 0xa4, 0xa7, 0xc7, 0xb1, 0x03, 0x5c, 0x38,
	0x71, 0xe7, 0xce, 0x05, 0x89, 0xd7, 0xe0, 0xc2, 0x1b, 0x20, 0x5e, 0x00, 0xf1, 0x10, 0x1c, 0x51,
	0xf7, 0xf4, 0xfe, 0x79, 0xd6, 0x51, 0x7c, 0xe0, 0x36, 0xf5, 0x75, 0x55, 0x75, 0xd5, 0x57, 0x3f,
	0x3d, 0xb0, 0xa6, 0x59, 0x36, 0x7a, 0x82, 0xa7, 0x18, 0xe6, 0x9a, 0x4b, 0xb1, 0x95, 0x2a, 0xa9,
	0x25, 0x59, 0x8d, 0xd9, 0x27, 0xf1, 0xb3, 0x27, 0xd3, 0xb3, 0xfe, 0x7a, 0x2c, 0x65, 0x3c, 0xc6,
	0x6d, 0x96, 0xf2, 0x6d, 0x26, 0x84, 0xd4, 0xcc, 0x68, 0x67, 0x85, 0x7a, 0xf0, 0xab, 0x07, 0xdd,
	0xc7, 0x2c, 0x1b, 0x0d, 0x98, 0x62, 0x09, 0x6a, 0x54, 0x84, 0x40, 0x4d, 0xb0, 0x04, 0x7d, 0x6f,
	0xc3, 0xdb, 0x6c, 0x53, 0xfb, 0x4d, 0x36, 0xa0, 0x13, 0x61, 0x16, 0x2a, 0x9e, 0x1a, 0x5b, 0xbf,
	0x62, 0x8f, 0xe6, 0x21, 0xd2, 0x87, 0xd6, 0x58, 0x86, 0xd6, 0xb5, 0x5f, 0xb5, 0xc7, 0x53, 0xd9,
	0x78, 0x4c, 0x99, 0x7e, 0xe6, 0xd7, 0x0a, 0x8f, 0xe6, 0x9b, 0xac, 0x41, 0x3d, 0x1c, 0xb3, 0x2c,
	0xf3, 0xeb, 0x16, 0x2c, 0x04, 0x72, 0x15, 0x1a, 0xa1, 0x42, 0xa6, 0xd1, 0x6f, 0x6c, 0x78, 0x9b,
	0x2d, 0xea, 0xa4, 0xe0, 0x18, 0x3a, 0x03, 0xa9, 0xf4, 0x23, 0x96, 0xa6, 0x5c, 0xc4, 0xe4, 0x03,
	0xe8, 0x86, 0x52, 0x68, 0xc6, 0x05, 0x2a, 0x83, 0xdb, 0x58, 0xeb, 0x74, 0x11, 0x34, 0x41, 0x3f,
	0x93, 0x99, 0xfe, 0x92, 0x8b, 0x88, 0x8b, 0xd8, 0x06, 0x5d, 0xa7, 0xf3, 0x50, 0xf0, 0xb7, 0x07,
	0x2b, 0x7b, 0x32, 0x1c, 0xa1, 0x7a, 0x60, 0x59, 0x94, 0x8a, 0xac, 0x43, 0x9b, 0x27, 0x2c, 0xc6,
	0xaf, 0x66, 0x14, 0xcc, 0x00, 0xd2, 0x83, 0x6a, 0x98, 0x44, 0x7e, 0x65, 0xa3, 0xba, 0xd9, 0xa6,
	0xe6, 0x93, 0xf8, 0xd0, 0x7c, 0x29, 0xd5, 0x28, 0xe2, 0xca, 0xa5, 0x3d, 0x11, 0x4d, 0x86, 0x99,
	0x8e, 0xb8, 0xb0, 0xa9, 0xb4, 0x69, 0x21, 0x98, 0x0c, 0x33, 0x1d, 0xc9, 0x5c, 0x3b, 0x36, 0x9c,
	0xe4, 0x70, 0x54, 0xca, 0x11, 0xe2, 0x24, 0x72, 0x1f, 0xae, 0xa4, 0x52, 0x4d, 0x22, 0xce, 0xfc,
	0xe6, 0x46, 0x75, 0xb3, 0xb3, 0xb3, 0xbe, 0x75, 0xae, 0xca, 0x5b, 0x73, 0xf4, 0xd0, 0x05, 0x8b,
	0xe0, 0x27, 0x0f, 0x1a, 0xdf, 0xc8, 0x71, 0x9e, 0xe0, 0xd2, 0xd2, 0x9a, 0x8b, 0xf9, 0x2b, 0xdc,
	0x1f, 0x5a, 0x82, 0x3c, 0xea, 0x24, 0x8b, 0xcb, 0x5c, 0x85, 0xe8, 0xf2, 0x72, 0x12, 0xb9, 0x0e,
	0x90, 0xc8, 0x5c, 0xe8, 0x81, 0xe4, 0x42, 0xbb, 0xdc, 0xe6, 0x10, 0xd3, 0x08, 0x0a, 0x59, 0x24,
	0xc5, 0xf8, 0xcc, 0x6f, 0xda, 0x22, 0x4e, 0xe5, 0xe0, 0x0f, 0x0f, 0xda, 0x14, 0x0b, 0x47, 0x19,
	0xd9, 0x84, 0xd5, 0x84, 0x0b, 0x9e, 0xe4, 0xc9, 0x6e, 0x9a, 0xef, 0x4a, 0x85, 0x99, 0x0d, 0xac,
	0x4b, 0xcf, 0xc3, 0xa6, 0x92, 0xa9, 0x42, 0x4c, 0x52, 0xcd, 0x87, 0x63, 0xb4, 0x81, 0xb6, 0xe8,
	0x3c, 0x44, 0x02, 0xb8, 0xe2, 0x8c, 0x28, 0x4b, 0xf6, 0x87, 0x36, 0x66, 0x8f, 0x2e, 0x60, 0xe4,
	0x0e, 0x34, 0x4f, 0x2c, 0x0f, 0x99, 0x5f, 0xb3, 0x2c, 0x5e, 0x2b, 0xb1, 0x58, 0xf0, 0x44, 0x27,
	0x7a, 0xa6, 0x86, 0xaf, 0xa4, 0x40, 0xd3, 0xa5, 0xa6, 0xe2, 0x85, 0x10, 0xfc, 0x5e, 0x81, 0x9a,
	0x99, 0x99, 0xa5, 0x7c, 0xae, 0x43, 0x3b, 0x55, 0xf2, 0x39, 0x86, 0xfa, 0x60, 0xcf, 0x0d, 0xca,
	0x0c, 0x38, 0x3f, 0x48, 0xd5, 0xf2, 0x20, 0x7d, 0x0a, 0x0d, 0x2e, 0xd2, 0x5c, 0x4f, 0x82, 0xbc,
	0x5e, 0x0a, 0x72, 0x61, 0x5c, 0xa9, 0xd3, 0x26, 0x77, 0xa1, 0x29, 0x73, 0x6d, 0x0d, 0xeb, 0x6f,
	0x64, 0x38, 0x51, 0x27, 0x77, 0xa1, 0xad, 0x26, 0x45, 0xb1, 0x05, 0xed, 0xec, 0xf4, 0x4b, 0xb6,
	0xd3, 0xb2, 0xd1, 0x99, 0x32, 0xf9, 0x0c, 0x1a, 0x91, 0x1d, 0x1f, 0xbf, 0x65, 0xaf, 0xbc, 0x51,
	0x32, 0x5b, 0x9c, 0x2e, 0xea, 0xd4, 0x4d, 0x4f, 0xae, 0x1c, 0xca, 0xe1, 0x43, 0x9e, 0x69, 0x8a,
	0x2f, 0x72, 0xcc, 0xf4, 0x22, 0x6f, 0xde, 0x79, 0xde, 0xae, 0x03, 0x18, 0x76, 0x07, 0x0a, 0x9f,
	0xf2, 0x53, 0x47, 0xeb, 0x1c, 0x62, 0xba, 0x2e, 0x65, 0x31, 0x1e, 0xf1, 0x57, 0x45, 0xbf, 0x76,
	0xe9, 0x54, 0xb6, 0x9e, 0x59, 0x8c, 0x8f, 0xe5, 0x08, 0x85, 0x9b, 0xba, 0x19, 0x10, 0x7c, 0x0b,
	0x2d, 0xc3, 0xcb, 0x1e, 0x66, 0xe1, 0xff, 0x51, 0xcf, 0xe0, 0x7b, 0x68, 0x1e, 0xca, 0xa1, 0x75,
	0xbf, 0x06, 0xf5, 0xe7, 0x72, 0x38, 0x4d, 0xaf, 0x10, 0xc8, 0x2d, 0xb3, 0x27, 0xcc, 0xca, 0x33,
	0xce, 0x57, 0x76, 0xae, 0x96, 0x38, 0x3c, 0x32, 0xa7, 0xb4, 0x50, 0x22, 0xb7, 0xa1, 0x66, 0x4e,
	0xec, 0x4d, 0x9d, 0x9d, 0x77, 0x97, 0xd6, 0xd8, 0x5c, 0x46, 0xad, 0x5a, 0x80, 0xb0, 0x3a, 0xe5,
	0x39, 0x4b, 0xa5, 0xc8, 0x90, 0xdc, 0x82, 0xda, 0x73, 0x39, 0x34, 0xb3, 0x66, 0x4a, 0xe6, 0x97,
	0x3c, 0xb8, 0x68, 0xa9, 0xd5, 0x32, 0xab, 0x56, 0xe0, 0xa9, 0x1e, 0x4c, 0x09, 0x2c, 0x28, 0x58,
	0x04, 0x83, 0xf7, 0xa0, 0x7e, 0x68, 0x93, 0x59, 0x83, 0xfa, 0x09, 0x1b, 0xe7, 0x13, 0x0a, 0x0b,
	0x21, 0xf8, 0xd7, 0x83, 0x86, 0x09, 0x43, 0xc6, 0x93, 0x0d, 0xea, 0xcd, 0x36, 0xe8, 0x3a, 0xb4,
	0x33, 0xcd, 0x94, 0x7e, 0xcc, 0x13, 0x9c, 0x10, 0x3c, 0x05, 0xcc, 0x7e, 0x45, 0x11, 0xd9, 0x33,
	0xb7, 0x5f, 0x9d, 0x78, 0xe9, 0x4d, 0xda, 0x87, 0x16, 0x9e, 0x72, 0xbd, 0x2b, 0xa3, 0xe2, 0x75,
	0xa9, 0xd3, 0xa9, 0x6c, 0x6c, 0xcc, 0xbb, 0x70, 0x30, 0xb0, 0x2b, 0xab, 0x4d, 0x9d, 0x54, 0xda,
	0xbe, 0xad, 0x4b, 0x6f, 0xdf, 0x5f, 0x2a, 0x50, 0x3d, 0x94, 0xc3, 0x0b, 0x6a, 0xff, 0x05, 0xb4,
	0x12, 0xd4, 0x2c, 0x62, 0x9a, 0xd9, 0x47, 0xa5, 0xb3, 0x13, 0x2c, 0xab, 0xc7, 0xd6, 0x23, 0xa7,
	0xf4, 0x40, 0x68, 0x75, 0x46, 0xa7, 0x36, 0xe4, 0xc3, 0x85, 0x6e, 0x78, 0x67, 0x69, 0x37, 0x14,
	0x9d, 0x30, 0x6b, 0xb3, 0xda, 0x9b, 0xb4, 0xd9, 0x47, 0x50, 0x1b, 0xcb, 0x78, 0xb2, 0x4a, 0xae,
	0x2d, 0x0b, 0xea, 0xa1, 0x8c, 0xa9, 0x55, 0xea, 0x7f, 0x0e, 0xdd, 0x85, 0x00, 0x4d, 0x91, 0x47,
	0x78, 0xe6, 0x52, 0x35, 0x9f, 0xb3, 0xbe, 0xa8, 0xcc, 0xf5, 0xc5, 0xbd, 0xca, 0x5d, 0x2f, 0x58,
	0x03, 0x72, 0x84, 0xea, 0x84, 0x87, 0x78, 0x20, 0x9e, 0x4a, 0xb7, 0x0d, 0x82, 0xdf, 0x3c, 0xe8,
	0xcc, 0xc1, 0xe4, 0x18, 0xba, 0x99, 0x96, 0x8a, 0xc5, 0xb8, 0x2b, 0xc5, 0x53, 0x1e, 0xbb, 0xee,
	0xdd, 0x2e, 0x67, 0x31, 0x33, 0xda, 0x3a, 0x9a, 0xb7, 0x28, 0xa8, 0x5b, 0xf4, 0xd2, 0xbf, 0x0f,
	0xa4, 0xac, 0x74, 0x99, 0xf0, 0x6f, 0xbe, 0x80, 0xba, 0x25, 0x8e, 0x74, 0xa0, 0x79, 0x2c, 0x46,
	0x42, 0xbe, 0x14, 0xbd, 0xb7, 0x08, 0x40, 0xe3, 0xeb, 0x1c, 0x73, 0x8c, 0x7a, 0x9e, 0x39, 0xa0,
	0xb9, 0x10, 0x5c, 0xc4, 0xbd, 0x8a, 0x39, 0x18, 0xb0, 0x3c, 0xc3, 0xa8, 0x57, 0x25, 0x57, 0xa0,
	0xb5, 0x2b, 0x93, 0x74, 0x8c, 0x1a, 0x7b, 0x35, 0xd2, 0x86, 0xfa, 0x03, 0xa5, 0xa4, 0xea, 0xd5,
	0xc9, 0x2a, 0x74, 0x8e, 0xce, 0x32, 0x8d, 0x49, 0x01, 0x34, 0xac, 0x26, 0x13, 0x21, 0x8e, 0x31,
	0xea, 0x35, 0x77, 0xfe, 0xaa, 0x42, 0xc7, 0x14, 0xd6, 0xa5, 0x4a, 0x12, 0x58, 0xd9, 0x47, 0x3d,
	0xcf, 0xd6, 0xfb, 0xaf, 0xa3, 0xc5, 0x51, 0xdc, 0x5f, 0x7f, 0x9d, 0x52, 0xe0, 0xff, 0xf8, 0xe7,
	0x3f, 0x3f, 0x57, 0x08, 0xe9, 0x6d, 0x9f, 0xdc, 0xd9, 0x36, 0x9b, 0xe0, 0x76, 0xe6, 0xae, 0x7b,
	0x64, 0xf3, 0xb1, 0xef, 0xdf, 0xf2, 0x86, 0xeb, 0x5f, 0x5d, 0xd6, 0x2e, 0x07, 0x7b, 0xc1, 0xdb,
	0xd6, 0x67, 0x37, 0x68, 0x4d, 0x7c, 0xde, 0xf3, 0x6e, 0x92, 0x27, 0xd0, 0x32, 0xeb, 0xe9, 0xd0,
	0x2c, 0x9b, 0x1b, 0x4b, 0xfb, 0x6c, 0xf6, 0x48, 0xf4, 0x37, 0x2e, 0x56, 0x28, 0xb6, 0x5b, 0xd0,
	0xb3, 0x77, 0x00, 0x99, 0xde, 0x41, 0x06, 0xd0, 0xd8, 0x47, 0xe3, 0x9f, 0x5c, 0x10, 0x57, 0x7f,
	0x6d, 0x19, 0x5e, 0x66, 0x60, 0xfb, 0x3b, 0x5b, 0xf6, 0x1f, 0xc8, 0x31, 0xb4, 0x8b, 0x72, 0xbc,
	0xce, 0xe9, 0x45, 0x24, 0x38, 0xb7, 0x37, 0x4b, 0x6e, 0x87, 0x0d, 0xfb, 0x47, 0xfe, 0xf1, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x62, 0x77, 0x61, 0xd8, 0x0b, 0x00, 0x00,
}
