apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: funnel-clusterrole
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
