{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: funnel-cluster-rolebinding-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: funnel-sa
    namespace: {{ .Release.Namespace }}
  {{- if and .Values.Kubernetes.JobsNamespace (ne .Values.Kubernetes.JobsNamespace .Values.Kubernetes.Namespace) }}
  - kind: ServiceAccount
    name: funnel-sa
    namespace: {{ .Values.Kubernetes.JobsNamespace }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: funnel-cluster-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
