apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: funnel-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: funnel-sa
  namespace: funnel
roleRef:
  kind: ClusterRole
  name: funnel-clusterrole
  apiGroup: rbac.authorization.k8s.io
