apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: funnel-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
