apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config
data:
  funnel-server-config.yaml: |-
    Database: boltdb

    Compute: kubernetes

    Logger:
      Level: debug

    Kubernetes:
      # The executor used to execute tasks. Available executors: docker, kubernetes
      Executor: "kubernetes"
      DisableJobCleanup: false
      DisableReconciler: false
      ReconcileRate: 5m
      Namespace: default
      Template: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          ## DO NOT CHANGE NAME
          name: {{.TaskId}}
          namespace: {{.Namespace}}
        spec:
          backoffLimit: 0
          completions: 1
          template:
            spec:
              restartPolicy: Never
              serviceAccountName: funnel-sa
              containers:
                - name: {{printf "funnel-worker-%s" .TaskId}}
                  image: quay.io/ohsu-comp-bio/funnel:latest
                  imagePullPolicy: IfNotPresent
                  args:
                    - "worker"
                    - "run"
                    - "--config"
                    - "/etc/config/funnel-worker-config.yaml"
                    - "--taskID"
                    - {{.TaskId}}
                  resources:
                      requests:
                        cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
                        memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
                        ephemeral-storage: {{if ne .DiskGb 0.0 -}}{{printf "%.0fG" .DiskGb}}{{else}}{{"100M"}}{{end}}
                  volumeMounts:
                    - name: {{printf "funnel-storage-%s" .TaskId}}
                      mountPath: {{printf "/opt/funnel/funnel-work-dir/%s" .TaskId}}
                    - name: config-volume
                      mountPath: /etc/config

                  securityContext:
                    privileged: true

              volumes:
                - name: {{printf "funnel-storage-%s" .TaskId}}
                  emptyDir: {}
                - name: config-volume
                  configMap:
                    name: funnel-config    

  funnel-worker-config.yaml: |-
    Database: boltdb
    BoltDB:
      Path: /opt/funnel/funnel-work-dir/funnel.bolt.db
    Compute: kubernetes
    Kubernetes:
      Executor: "kubernetes"
    Logger:
      Level: debug
    RPCClient:
      MaxRetries: 3
      Timeout: 30s
    EventWriters:
      - rpc
      - log
    Server:
      HostName: ""
      RPCPort: 9090
