apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "funnel.fullname" . }}
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "funnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "funnel.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "funnel.serviceAccountName" . }}
      containers:
        - name: funnel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command:
            - 'funnel'
            - 'server'
            - 'run'
            - '--config'
            - '/etc/config/funnel-server-config.yaml'
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - name: http
              containerPort: 8000
            - name: rpc
              containerPort: 9090
          volumeMounts:
            - name: funnel-deployment-storage
              mountPath: /opt/funnel/funnel-work-dir
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: funnel-deployment-storage
          persistentVolumeClaim:
            claimName: funnel-pvc
        - name: config-volume
          configMap:
            name: funnel-config
