Database: boltdb
BoltDB:
  Path: /opt/funnel/funnel-work-dir/funnel.bolt.db
Compute: kubernetes
Kubernetes:
  Executor: "kubernetes"
Logger:
  Level: debug
RPCClient:
  MaxRetries: 3
  Timeout: 30s
EventWriters:
  - rpc
  - log
Server:
  HostName: {{ .Values.server.hostname | default "" }}
  RPCPort: {{ .Values.server.rpcPort | default 9090 }}
