apiVersion: v1
kind: Service
metadata:
  name: {{ include "funnel.fullname" . }}
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: rpc
      protocol: TCP
      port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
  selector:
    {{- include "funnel.selectorLabels" . | nindent 4 }}
