{{- if .Values.storage.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: funnel-server-pv
  namespace: {{ .Release.Namespace }} 
  labels:
    app.kubernetes.io/name: funnel
    app.kubernetes.io/instance: funnel
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes: 
    - ReadWriteOnce
  storageClassName: "gp2"
  volumeMode: {{ .Values.storage.volumeMode }}
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/mnt/data"
{{- end }}
