apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "funnel-server" }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # This ensures only one pod is unavailable during the update process
      maxSurge: 0        # No new pod is created until the old one is fully terminated
  selector:
    matchLabels:
      {{- include "funnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "funnel.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        checksum/values: {{ .Values | quote | sha256sum }}
    spec:
      serviceAccountName: funnel-sa-{{ .Release.Namespace }}
      {{ if .Values.Plugins }}
      initContainers:
        - name: plugins
          image: {{ .Values.image.initContainer.image }}:{{ .Values.image.initContainer.tag }}
          imagePullPolicy: Always
          volumeMounts:
          - name: plugin-volume
            mountPath: /opt/funnel/plugin-binaries
          command: {{- range .Values.image.initContainer.command }}
            - {{ . }}
          {{- end }}
      {{ end }}
      containers:
        - name: funnel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 3600; done"]
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - name: http
              containerPort: 8000
            - name: rpc
              containerPort: 9090
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "ls /"]
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "ls /"]
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

            - name: worker-templates-volume
              mountPath: /etc/funnel/templates

            - name: plugin-volume
              mountPath: /opt/funnel/plugin-binaries

      volumes:
        - name: config-volume
          configMap:
            name: funnel-server-config

        - name: worker-templates-volume
          configMap:
            name: funnel-worker-templates

        - name: plugin-volume
          emptyDir: {}  # Shared volume
