apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "funnel-server-pvc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.storage.size | default "10Mi" }}
  storageClassName: "gp2"