{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "funnel.serviceAccountName" . }}
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
