{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funnel-sa-{{ .Release.Namespace }}
  namespace: {{ .Values.Kubernetes.Namespace }}
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- if and .Values.Kubernetes.JobsNamespace (ne .Values.Kubernetes.JobsNamespace .Values.Kubernetes.Namespace) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funnel-sa-{{ .Release.Namespace }}
  namespace: {{ .Values.Kubernetes.JobsNamespace }}
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
