package mocks

import config "funnel/config"
import pbf "funnel/proto/funnel"

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// StartWorker provides a mock function with given fields: tplName, conf
func (_m *Client) StartWorker(tplName string, conf config.Worker) error {
	ret := _m.Called(tplName, conf)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, config.Worker) error); ok {
		r0 = rf(tplName, conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Templates provides a mock function with given fields:
func (_m *Client) Templates() []pbf.Worker {
	ret := _m.Called()

	var r0 []pbf.Worker
	if rf, ok := ret.Get(0).(func() []pbf.Worker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pbf.Worker)
		}
	}

	return r0
}
