// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	scheduler.proto

It has these top-level messages:
	Resources
	Node
	ListNodesRequest
	ListNodesResponse
	UpdateNodeResponse
	GetNodeRequest
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeState int32

const (
	NodeState_UNINITIALIZED NodeState = 0
	NodeState_ALIVE         NodeState = 1
	NodeState_DEAD          NodeState = 2
	NodeState_GONE          NodeState = 3
	NodeState_INITIALIZING  NodeState = 4
)

var NodeState_name = map[int32]string{
	0: "UNINITIALIZED",
	1: "ALIVE",
	2: "DEAD",
	3: "GONE",
	4: "INITIALIZING",
}
var NodeState_value = map[string]int32{
	"UNINITIALIZED": 0,
	"ALIVE":         1,
	"DEAD":          2,
	"GONE":          3,
	"INITIALIZING":  4,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}
func (NodeState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Resources struct {
	Cpus uint32 `protobuf:"varint,1,opt,name=cpus" json:"cpus,omitempty"`
	// In GB
	RamGb float64 `protobuf:"fixed64,2,opt,name=ram_gb,json=ramGb" json:"ram_gb,omitempty"`
	// In GB
	DiskGb float64 `protobuf:"fixed64,3,opt,name=disk_gb,json=diskGb" json:"disk_gb,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resources) GetCpus() uint32 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Resources) GetRamGb() float64 {
	if m != nil {
		return m.RamGb
	}
	return 0
}

func (m *Resources) GetDiskGb() float64 {
	if m != nil {
		return m.DiskGb
	}
	return 0
}

type Node struct {
	Id          string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Resources   *Resources `protobuf:"bytes,5,opt,name=resources" json:"resources,omitempty"`
	Available   *Resources `protobuf:"bytes,6,opt,name=available" json:"available,omitempty"`
	LastPing    int64      `protobuf:"varint,7,opt,name=last_ping,json=lastPing" json:"last_ping,omitempty"`
	State       NodeState  `protobuf:"varint,8,opt,name=state,enum=scheduler.NodeState" json:"state,omitempty"`
	Preemptible bool       `protobuf:"varint,9,opt,name=preemptible" json:"preemptible,omitempty"`
	ActivePorts []int32    `protobuf:"varint,10,rep,packed,name=active_ports,json=activePorts" json:"active_ports,omitempty"`
	Zone        string     `protobuf:"bytes,11,opt,name=zone" json:"zone,omitempty"`
	Hostname    string     `protobuf:"bytes,13,opt,name=hostname" json:"hostname,omitempty"`
	// Version of the record in the database. Used to prevent write conflicts.
	Version  int64             `protobuf:"varint,14,opt,name=version" json:"version,omitempty"`
	Metadata map[string]string `protobuf:"bytes,15,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaskIds  []string          `protobuf:"bytes,16,rep,name=task_ids,json=taskIds" json:"task_ids,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Node) GetAvailable() *Resources {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *Node) GetLastPing() int64 {
	if m != nil {
		return m.LastPing
	}
	return 0
}

func (m *Node) GetState() NodeState {
	if m != nil {
		return m.State
	}
	return NodeState_UNINITIALIZED
}

func (m *Node) GetPreemptible() bool {
	if m != nil {
		return m.Preemptible
	}
	return false
}

func (m *Node) GetActivePorts() []int32 {
	if m != nil {
		return m.ActivePorts
	}
	return nil
}

func (m *Node) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Node) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Node) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Node) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetTaskIds() []string {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

type ListNodesRequest struct {
}

func (m *ListNodesRequest) Reset()                    { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()               {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListNodesResponse struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ListNodesResponse) Reset()                    { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()               {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListNodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type UpdateNodeResponse struct {
}

func (m *UpdateNodeResponse) Reset()                    { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()               {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetNodeRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetNodeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Resources)(nil), "scheduler.Resources")
	proto.RegisterType((*Node)(nil), "scheduler.Node")
	proto.RegisterType((*ListNodesRequest)(nil), "scheduler.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "scheduler.ListNodesResponse")
	proto.RegisterType((*UpdateNodeResponse)(nil), "scheduler.UpdateNodeResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "scheduler.GetNodeRequest")
	proto.RegisterEnum("scheduler.NodeState", NodeState_name, NodeState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SchedulerService service

type SchedulerServiceClient interface {
	UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error)
}

type schedulerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerServiceClient(cc *grpc.ClientConn) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	out := new(UpdateNodeResponse)
	err := grpc.Invoke(ctx, "/scheduler.SchedulerService/UpdateNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := grpc.Invoke(ctx, "/scheduler.SchedulerService/ListNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/scheduler.SchedulerService/GetNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SchedulerService service

type SchedulerServiceServer interface {
	UpdateNode(context.Context, *Node) (*UpdateNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*Node, error)
}

func RegisterSchedulerServiceServer(s *grpc.Server, srv SchedulerServiceServer) {
	s.RegisterService(&_SchedulerService_serviceDesc, srv)
}

func _SchedulerService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.SchedulerService/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).UpdateNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.SchedulerService/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.SchedulerService/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedulerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateNode",
			Handler:    _SchedulerService_UpdateNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _SchedulerService_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _SchedulerService_GetNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0x8e, 0x2c, 0xff, 0x48, 0xe3, 0xd8, 0x51, 0x86, 0xb4, 0xdd, 0x38, 0x29, 0xa8, 0x82, 0x82,
	0xc8, 0x21, 0xa6, 0xee, 0xa5, 0x4d, 0xa1, 0x10, 0x88, 0x31, 0x82, 0xc4, 0x09, 0x9b, 0xa6, 0xd0,
	0x5e, 0xcc, 0xda, 0x5a, 0x9c, 0x25, 0xb6, 0xa4, 0x6a, 0xd7, 0x86, 0xb4, 0xf4, 0xd2, 0x57, 0xe8,
	0xa3, 0xf5, 0x15, 0x7a, 0xe9, 0x3b, 0xf4, 0x50, 0x76, 0xed, 0x28, 0x8e, 0x09, 0xbd, 0xcd, 0x7c,
	0xf3, 0xcd, 0xcc, 0xa7, 0x6f, 0x16, 0xc1, 0x96, 0x1c, 0x5d, 0xf3, 0x78, 0x36, 0xe1, 0xf9, 0x61,
	0x96, 0xa7, 0x2a, 0x45, 0xb7, 0x00, 0x5a, 0xfb, 0xe3, 0x34, 0x1d, 0x4f, 0x78, 0x9b, 0x65, 0xa2,
	0xcd, 0x92, 0x24, 0x55, 0x4c, 0x89, 0x34, 0x91, 0x0b, 0x62, 0x70, 0x0e, 0x2e, 0xe5, 0x32, 0x9d,
	0xe5, 0x23, 0x2e, 0x11, 0xa1, 0x3c, 0xca, 0x66, 0x92, 0x58, 0xbe, 0x15, 0x36, 0xa8, 0x89, 0xf1,
	0x09, 0x54, 0x73, 0x36, 0x1d, 0x8c, 0x87, 0xa4, 0xe4, 0x5b, 0xa1, 0x45, 0x2b, 0x39, 0x9b, 0xf6,
	0x86, 0xf8, 0x0c, 0x6a, 0xb1, 0x90, 0x37, 0x1a, 0xb7, 0x0d, 0x5e, 0xd5, 0x69, 0x6f, 0x18, 0xfc,
	0xb1, 0xa1, 0xdc, 0x4f, 0x63, 0x8e, 0x4d, 0x28, 0x89, 0xd8, 0x8c, 0x72, 0x69, 0x49, 0xc4, 0xd8,
	0x01, 0x37, 0xbf, 0xdb, 0x44, 0x2a, 0xbe, 0x15, 0xd6, 0x3b, 0x3b, 0x87, 0xf7, 0xba, 0x0b, 0x15,
	0xf4, 0x9e, 0xa6, 0x7b, 0xd8, 0x9c, 0x89, 0x09, 0x1b, 0x4e, 0x38, 0xa9, 0xfe, 0xaf, 0xa7, 0xa0,
	0xe1, 0x1e, 0xb8, 0x13, 0x26, 0xd5, 0x20, 0x13, 0xc9, 0x98, 0xd4, 0x7c, 0x2b, 0xb4, 0xa9, 0xa3,
	0x81, 0x0b, 0x91, 0x8c, 0xf1, 0x00, 0x2a, 0x52, 0x31, 0xc5, 0x89, 0xe3, 0x5b, 0x61, 0xf3, 0xc1,
	0x30, 0x2d, 0xfa, 0x52, 0xd7, 0xe8, 0x82, 0x82, 0x3e, 0xd4, 0xb3, 0x9c, 0xf3, 0x69, 0xa6, 0x84,
	0x5e, 0xef, 0xfa, 0x56, 0xe8, 0xd0, 0x55, 0x08, 0x5f, 0xc0, 0x26, 0x1b, 0x29, 0x31, 0xe7, 0x83,
	0x2c, 0xcd, 0x95, 0x24, 0xe0, 0xdb, 0x61, 0x85, 0xd6, 0x17, 0xd8, 0x85, 0x86, 0xb4, 0xa5, 0x5f,
	0xd3, 0x84, 0x93, 0xba, 0xf1, 0xc1, 0xc4, 0xd8, 0x02, 0xe7, 0x3a, 0x95, 0x2a, 0x61, 0x53, 0x4e,
	0x1a, 0x06, 0x2f, 0x72, 0x24, 0x50, 0x9b, 0xf3, 0x5c, 0x8a, 0x34, 0x21, 0x4d, 0xa3, 0xfd, 0x2e,
	0xc5, 0xb7, 0xe0, 0x4c, 0xb9, 0x62, 0x31, 0x53, 0x8c, 0x6c, 0xf9, 0x76, 0x58, 0xef, 0x3c, 0x5f,
	0x53, 0x7f, 0x78, 0xb6, 0xac, 0x77, 0x13, 0x95, 0xdf, 0xd2, 0x82, 0x8e, 0xbb, 0xe0, 0x28, 0x26,
	0x6f, 0x06, 0x22, 0x96, 0xc4, 0xf3, 0xed, 0xd0, 0xa5, 0x35, 0x9d, 0x47, 0xb1, 0x6c, 0xbd, 0x83,
	0xc6, 0x83, 0x2e, 0xf4, 0xc0, 0xbe, 0xe1, 0xb7, 0xcb, 0xbb, 0xe9, 0x10, 0x77, 0xa0, 0x32, 0x67,
	0x93, 0x19, 0x37, 0x0f, 0xc0, 0xa5, 0x8b, 0xe4, 0xa8, 0xf4, 0xc6, 0x0a, 0x10, 0xbc, 0x53, 0x21,
	0x95, 0xde, 0x2d, 0x29, 0xff, 0x32, 0xe3, 0x52, 0x05, 0x47, 0xb0, 0xbd, 0x82, 0xc9, 0x2c, 0x4d,
	0x24, 0xc7, 0x97, 0x50, 0x49, 0x34, 0x40, 0x2c, 0x23, 0x7c, 0x6b, 0x4d, 0x38, 0x5d, 0x54, 0x83,
	0x1d, 0xc0, 0xab, 0x2c, 0x66, 0x8a, 0x1b, 0x70, 0xd9, 0x1c, 0xf8, 0xd0, 0xec, 0x71, 0xb5, 0x80,
	0xcc, 0x8e, 0xf5, 0xa7, 0x75, 0x70, 0x0e, 0x6e, 0x71, 0x3d, 0xdc, 0x86, 0xc6, 0x55, 0x3f, 0xea,
	0x47, 0x1f, 0xa2, 0xe3, 0xd3, 0xe8, 0x73, 0xf7, 0xc4, 0xdb, 0x40, 0x17, 0x2a, 0xc7, 0xa7, 0xd1,
	0xc7, 0xae, 0x67, 0xa1, 0x03, 0xe5, 0x93, 0xee, 0xf1, 0x89, 0x57, 0xd2, 0x51, 0xef, 0xbc, 0xdf,
	0xf5, 0x6c, 0xf4, 0x60, 0xb3, 0xe0, 0x47, 0xfd, 0x9e, 0x57, 0xee, 0xfc, 0xb5, 0xc0, 0xbb, 0xbc,
	0x93, 0x78, 0xc9, 0xf3, 0xb9, 0x18, 0x71, 0x7c, 0x0f, 0x70, 0xaf, 0x0e, 0xd7, 0xbf, 0xa1, 0xb5,
	0x7a, 0x8d, 0x47, 0xbe, 0x62, 0x03, 0x3f, 0x81, 0x5b, 0x38, 0x83, 0x7b, 0x2b, 0xec, 0x75, 0x0f,
	0x5b, 0xfb, 0x8f, 0x17, 0x97, 0x93, 0xb6, 0x7f, 0xfc, 0xfa, 0xfd, 0xb3, 0x54, 0x47, 0xb7, 0x3d,
	0x7f, 0xd5, 0x36, 0xc6, 0xe1, 0x19, 0xd4, 0x96, 0x16, 0xe1, 0xee, 0x4a, 0xef, 0x43, 0xdb, 0x5a,
	0xeb, 0x92, 0x83, 0xa7, 0x66, 0x92, 0x87, 0xcd, 0x62, 0x52, 0xfb, 0x9b, 0x88, 0xbf, 0x0f, 0xab,
	0xe6, 0xdf, 0xf0, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xc2, 0x8a, 0xde, 0x57, 0x04,
	0x00, 0x00,
}
