# Task Executor

apiVersion: batch/v1
kind: Job
metadata:
  name: {{.TaskId}}-{{.JobId}}
  namespace: {{.Namespace}}
  labels:
    job-name: {{.TaskId}}-{{.JobId}}
spec: 
  backoffLimit: 0
  completions: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: funnel-sa
      containers: 
      - name: funnel-worker-{{.TaskId}}
        image: {{.Image}}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: {{.Command}}
        workingDir: {{.Workdir}}
        resources:
          requests:
            cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
            memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
            ephemeral-storage: {{if ne .DiskGb 0.0 -}}{{printf "%.0fG" .DiskGb}}{{else}}{{"100M"}}{{end}}
        volumeMounts:
          - name: worker-storage
            mountPath: /opt/funnel    # Mount the same shared directory

      volumes:
        - name: worker-storage
          emptyDir: {}  # Uses same configuration as worker