apiVersion: batch/v1
kind: Job
metadata:
  ## DO NOT CHANGE NAME
  name: {{.TaskId}}
  namespace: {{.Namespace}}
spec: 
  backoffLimit: 0
  completions: 1
  template:
    spec:
      serviceAccountName: funnel-sa
      restartPolicy: Never
      containers: 
        - name: funnel-worker-{{.TaskId}}
          image: ohsucompbio/funnel-dind-rootless:latest
          imagePullPolicy: Always
          args:
            - "worker"
            - "run"
            - "--config"
            - "/etc/config/funnel-worker-config.yml"
            - "--taskID"
            - {{.TaskId}}
          resources:
              requests:
                cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
                memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
                ephemeral-storage: {{if ne .DiskGb 0.0 -}}{{printf "%.0fG" .DiskGb}}{{else}}{{"100M"}}{{end}}
          volumeMounts:
            - name: funnel-storage-{{.TaskId}}
              mountPath: /opt/funnel/funnel-work-dir/{{.TaskId}}
              subPath: {{.TaskId}}
            - name: config-volume
              mountPath: /etc/config

      volumes: 
        - name: config-volume
          configMap:
            name: funnel-config
        - name: funnel-storage-{{.TaskId}}
          persistentVolumeClaim:
            claimName: storage-pvc 