LocalStorage:
  # Whitelist of local directory paths which Funnel is allowed to access.
  AllowedDirs:
    - ./
    - /tmp

Worker:
  LeaveWorkDir: true
  ContainerEngine: exadocker
  ContainerCommand: sudo /opt/acc/sbin/exadocker

Server:
  HostName: exahead1

Compute: slurm

Slurm:
  Template: |
    #!/bin/bash
    #SBATCH --job-name {{.TaskId}}
    #SBATCH --ntasks 1
    #SBATCH --error {{.WorkDir}}/funnel-stderr
    #SBATCH --output {{.WorkDir}}/funnel-stdout
    #SBATCH --gres disk:1
    {{if ne .Cpus 0 -}}
    {{printf "#SBATCH --cpus-per-task %d" .Cpus}}
    {{- end}}
    {{if ne .RamGb 0.0 -}}
    {{printf "#SBATCH --mem %.0fGB" .RamGb}}
    {{- end}}
    {{if ne .DiskGb 0.0 -}}
    {{printf "#SBATCH --tmp %.0fGB" .DiskGb}}
    {{- end}}

    srun /usr/local/bin/mkdir-scratch.sh
    SCRATCH_PATH="/mnt/scratch/${SLURM_JOB_ID}"
    cd $SCRATCH_PATH
    srun bash -c 'funnel worker run --taskID {{.TaskId}} {{.Args}}' --temp-dir $SCRATCH_PATH
    cd -
    srun /usr/local/bin/rmdir-scratch.sh

