apiVersion: v1
kind: ServiceAccount
metadata:
  name: funnel-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: funnel-rolebinding
subjects:
  - kind: ServiceAccount
    name: funnel-sa
roleRef:
  kind: Role
  name: funnel-role
  apiGroup: rbac.authorization.k8s.io
