apiVersion: v1
kind: Service
metadata:
  name: funnel
spec:
  selector:
    app: funnel
  ports:
    - name: funnel
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9090
      targetPort: 9090
