package mocks

import context "golang.org/x/net/context"
import events "github.com/ohsu-comp-bio/funnel/events"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import protoscheduler "github.com/ohsu-comp-bio/funnel/proto/scheduler"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() {
	_m.Called()
}

// DeleteNode provides a mock function with given fields: ctx, in, opts
func (_m *Client) DeleteNode(ctx context.Context, in *protoscheduler.Node, opts ...grpc.CallOption) (*protoscheduler.DeleteNodeResponse, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *protoscheduler.DeleteNodeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *protoscheduler.Node, ...grpc.CallOption) *protoscheduler.DeleteNodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protoscheduler.DeleteNodeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protoscheduler.Node, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNode provides a mock function with given fields: ctx, in, opts
func (_m *Client) GetNode(ctx context.Context, in *protoscheduler.GetNodeRequest, opts ...grpc.CallOption) (*protoscheduler.Node, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *protoscheduler.Node
	if rf, ok := ret.Get(0).(func(context.Context, *protoscheduler.GetNodeRequest, ...grpc.CallOption) *protoscheduler.Node); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protoscheduler.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protoscheduler.GetNodeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNodes provides a mock function with given fields: ctx, in, opts
func (_m *Client) ListNodes(ctx context.Context, in *protoscheduler.ListNodesRequest, opts ...grpc.CallOption) (*protoscheduler.ListNodesResponse, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *protoscheduler.ListNodesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *protoscheduler.ListNodesRequest, ...grpc.CallOption) *protoscheduler.ListNodesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protoscheduler.ListNodesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protoscheduler.ListNodesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutNode provides a mock function with given fields: ctx, in, opts
func (_m *Client) PutNode(ctx context.Context, in *protoscheduler.Node, opts ...grpc.CallOption) (*protoscheduler.PutNodeResponse, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *protoscheduler.PutNodeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *protoscheduler.Node, ...grpc.CallOption) *protoscheduler.PutNodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protoscheduler.PutNodeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protoscheduler.Node, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteEvent provides a mock function with given fields: ctx, in, opts
func (_m *Client) WriteEvent(ctx context.Context, in *events.Event, opts ...grpc.CallOption) (*events.WriteEventResponse, error) {
	ret := _m.Called(ctx, in, opts)

	var r0 *events.WriteEventResponse
	if rf, ok := ret.Get(0).(func(context.Context, *events.Event, ...grpc.CallOption) *events.WriteEventResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*events.WriteEventResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *events.Event, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
