apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "funnel.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # This ensures only one pod is unavailable during the update process
      maxSurge: 0        # No new pod is created until the old one is fully terminated
  selector:
    matchLabels:
      {{- include "funnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "funnel.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/values: {{ .Values | quote | sha256sum }}
    spec:
      serviceAccountName: {{ include "funnel.serviceAccountName" . }}
      containers:
        - name: funnel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command:
            - 'funnel'
            - 'server'
            - 'run'
            - '--config'
            - '/etc/config/funnel-server.yaml'
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - name: http
              containerPort: 8000
            - name: rpc
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: funnel-deployment-storage
              mountPath: /opt/funnel/funnel-work-dir
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: funnel-deployment-storage
          persistentVolumeClaim:
            claimName: funnel-pvc
        - name: config-volume
          configMap:
            name: funnel-config
