{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": "keep"  # Ensures Helm doesn't delete this PVC
spec:
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "10Gi" }}
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className | quote }}
  {{- end }}
{{- end }}
