apiVersion: v1
kind: Service
metadata:
  name: funnel
  namespace: {{ .Release.Namespace }} 
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: rpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    {{- include "funnel.selectorLabels" . | nindent 4 }}
