{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funnel-sa
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "funnel.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
