name: Build

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Store funnel
      uses: actions/upload-artifact@v2
      with:
        name: funnelBin
        path: funnel