# Publishes releases to GitHub when a new semver tag is pushed
# Ref: https://semver.org

name: Release
on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # Add Tmate step
      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3          
        env:
          REF: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
        run: |
          export GIT_BRANCH=$(git branch -r --contains ${{ github.ref }}) --format "%(refname:lstrip=3)"
          export PATH="$HOME/go/bin:$PATH"
          make release
