# Credit: rhnvrm
# Adapted from: https://rohanverma.net/blog/2021/02/09/minio-github-actions/

name: S3 Integration Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Store funnel
      uses: actions/upload-artifact@v2
      with:
        name: funnelBin
        path: funnel
  
  s3Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ROOT_USER=minioadmin" \
                     -e "MINIO_ROOT_PASSWORD=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data

      - uses: actions/download-artifact@v3
        with:
          name: funnelBin

      - name: Start Funnel server
        run: |
          cat <<EOF > config.yml
            LocalStorage:
              Disabled: true
            AmazonS3:
              Disabled: true
            GoogleStorage:
              Disabled: true
            HTTPStorage:
              Disabled: true
            FTPStorage:
              Disabled: true
            GenericS3:
              - Disabled: false
                Endpoint: "localhost:9000"
                Key: "minioadmin"
                Secret: "minioadmin"
          EOF
          chmod +x funnel
          ./funnel server run --config `pwd`/config.yml &> funnel.logs &
          ./funnel task run examples/s3-test.yml
