name: Go

on: [ pull_request ]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m --verbose --disable unused --exclude "deprecated"

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./

    - name: Store funnel
      uses: actions/upload-artifact@v2
      with:
        name: funnelBin
        path: funnel

  unitTest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
    - name: Check out code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: make test
