name: Go

on: [ pull_request ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint dependencies
      run: make lint-depends

    - name: Lint
      run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./

    - name: Store funnel
      uses: actions/upload-artifact@v2
      with:
        name: funnelBin
        path: funnel

  unitTest:
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Check out code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: make test
