name: Go Tests

on:
  push:

# Cancel redundant jobs (if a new job is triggered for the same workflow and ref)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          # https://github.com/golangci/golangci-lint/releases/tag/v2.11.4
          version: v2.11.4
          args: |
              golangci-lint run \
              --timeout 3m --disable-all --enable=govet --enable=gofmt --enable=goimports --enable=misspell \
              --exclude-dirs "vendor" \
              --exclude-dirs "webdash" \
              --exclude-dirs "cmd/webdash" \
              --exclude-dirs "funnel-work-dir" \
              -e '.*bundle.go' -e ".*pb.go" -e ".*pb.gw.go" \
              ./...

  # unitTest:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code
  #     uses: actions/checkout@v4

  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v5
  #     with:
  #       go-version-file: go.mod

  #   - name: Unit Tests
  #     run: |
  #       go test -v ./... -coverprofile=coverage.out
  #       go tool cover -func=coverage.out