name: Workflow Tests

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: 
      - '**'

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download funnel
      uses: actions/download-artifact@v2
      with:
        name: funnelBin
        path: funnel

    - name: Run Nextflow test (nf-canary)
      run: |
        chmod +x funnel
        funnel server run --config funnel.config
        funnel task create examples/nextflow.json
    
