#!/bin/bash
# Create a custom Funnel image.
# This expects to run on a GCE VM.

source ./helpers.sh
./install-deps.sh

vm_name=$(hostname)
# Get zone from instance metadata
zone=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor:Google" | cut -d'/' -f4)
image_name="funnel-$(date +%s)"

gcloud config set compute/zone $zone

###########################################################
log_header "Making snapshot: $image_name"

gcloud compute disks snapshot $vm_name --snapshot-names $image_name

###########################################################
log_header "Making disk from snapshot: $image_name"

gcloud compute disks create $image_name --source-snapshot $image_name

###########################################################
log_header "Deleting snapshot"

gcloud compute --quiet snapshots delete $image_name

###########################################################
log_header "Making image from disk: $image_name"

gcloud compute images create $image_name --family funnel --source-disk $image_name

###########################################################
log_header "Deleting disk"

gcloud compute --quiet disks delete $image_name

###########################################################
log_header "Deleting instance: $vm_name"

gcloud compute --quiet instances delete $vm_name
